//! Words for what systems declare about themselves, the shelves and the seven examples.

zk_i18n::messages! {
    ShelfZcash { en: "Zcash" },
    ShelfAztec { en: "Aztec" },
    ShelfPolygon { en: "Polygon" },
    ShelfOthers { en: "Others" },
    ShelfHomemade { en: "Homemade" },
    NoSystems { en: "No proof systems are built into this binary yet." },
    NoSystemsDetail { en: "The examples and every command work; there is nothing to run until systems are wired into zk-registry." },
    ListTitle { en: "Systems in this build: {count}" },
    ShelfEmpty { en: "Nothing on the {shelf} shelf in this build." },
    ListFooter { en: "/about <system> tells its story · /run <system> <example> runs it" },
    ColId { en: "ID" },
    ColName { en: "Name" },
    ColYear { en: "Year" },
    ColSetup { en: "Trusted setup" },
    ColZk { en: "Zero-knowledge" },
    ColProofSize { en: "Proof size" },
    ColCode { en: "Code" },
    SetupNone { en: "none" },
    SetupUniversal { en: "universal" },
    SetupPerCircuit { en: "per circuit" },
    SetupTrusted { en: "trusted component" },
    ZkYes { en: "yes" },
    ZkNo { en: "no" },
    ZkOptional { en: "optional" },
    AssumePairing { en: "pairings" },
    AssumeDiscreteLog { en: "discrete logarithm" },
    AssumeHash { en: "hash functions" },
    AssumeLattice { en: "lattices" },
    AssumeTrusted { en: "a trusted component" },
    SizeConstant { en: "constant" },
    SizeLog { en: "logarithmic" },
    SizePolylog { en: "polylogarithmic" },
    SizeSqrt { en: "square root" },
    SizeLinear { en: "linear" },
    RecNone { en: "none" },
    RecRecursion { en: "recursion" },
    RecAccumulation { en: "accumulation" },
    RecFolding { en: "folding" },
    ModeNonInteractive { en: "non-interactive proof" },
    ModeInteractive { en: "live conversation" },
    CodeUpstream { en: "upstream" },
    CodeTeaching { en: "teaching" },
    CodeCompanion { en: "companion" },
    CodeHomemade { en: "homemade" },
    ImplUpstream { en: "{name} {version} ({license})" },
    ImplTeaching { en: "teaching implementation · not audited, built on {crates}" },
    ImplCompanion { en: "companion executable nmtzk-{id}, running {upstream}" },
    ImplHomemade { en: "designed for this repository" },
    StatusActive { en: "in use" },
    StatusSuperseded { en: "superseded by {by} since {since}" },
    StatusDiscontinued { en: "discontinued since {since}" },
    StatusExperimental { en: "experimental" },
    StatusHistorical { en: "historical" },
    StatusAsOf { en: "{status} (as of {date})" },
    LabelAuthors { en: "Authors" },
    LabelPaper { en: "Paper" },
    LabelSetup { en: "Trusted setup" },
    LabelZk { en: "Zero-knowledge" },
    LabelAssumptions { en: "Assumptions" },
    LabelPostQuantum { en: "Post-quantum" },
    LabelProofSize { en: "Proof size" },
    LabelRecursion { en: "Recursion" },
    LabelMode { en: "Mode" },
    LabelField { en: "Field" },
    LabelCode { en: "Code" },
    LabelStatus { en: "Status" },
    LabelUsedIn { en: "Used in" },
    Yes { en: "yes" },
    No { en: "no" },
    PaperLine { en: "{title}, {venue}" },
    DeploymentSince { en: "{project} (since {since})" },
    DeploymentRange { en: "{project} ({since} to {until})" },
    AboutPage { en: "ctrl+o opens the page again." },
    AboutNoPage { en: "No page has been written for {system} yet." },
    AboutNotBuilt { en: "{system} is not built into this binary; showing its page." },
    CautionTeaching { en: "Teaching implementation · not audited" },
    CautionNotZk { en: "Not zero-knowledge as run here: succinct is not the same as zero-knowledge." },
    CautionOptionalZk { en: "Zero knowledge is optional in this system; its page says which setting runs here." },
    CautionTrusted { en: "Trusted component: security rests on a part everyone must trust, not on mathematics." },
    ExamplesTitle { en: "Seven statements. Every system proves the same circuit." },
    ExamplesInputs { en: "public: {public} · private: {private}" },
    ExamplesMany { en: "{first} … {last} ({count} in all)" },
    ExamplesToyHash { en: "Envelopes and digests use ToyHash, a toy for teaching and not a real hash." },
    ExOnePlusOne { en: "The answer sealed in this envelope is 1 + 1." },
    ExPassword { en: "I know the PIN behind this digest." },
    ExSudoku { en: "I solved this 4×4 sudoku." },
    ExAge { en: "I am at least 18." },
    ExMembership { en: "I am one of 16 members, without saying which." },
    ExFactoring { en: "I know two factors of N, neither of them 1." },
    ExPoolSpend { en: "A spend in the Toy Shielded Pool." },
    ExPoolSpendNoRangeChecks { en: "A pool spend with the range checks removed, to show a counterfeit getting through." },
    ExPoolSpendUnboundNullifier { en: "A pool spend whose nullifier is not bound to the note, to show a double spend getting through." },
}
