//! Words for what systems declare about themselves, the shelves and the seven examples.

zk_i18n::messages! {
    ShelfZcash { en: "Zcash", ko: "Zcash" },
    ShelfAztec { en: "Aztec", ko: "Aztec" },
    ShelfPolygon { en: "Polygon", ko: "Polygon" },
    ShelfOthers { en: "Others" },
    ShelfHomemade { en: "Homemade" },
    NoSystems { en: "No proof systems are built into this binary yet.", ko: "이 실행 파일에는 아직 증명 시스템이 들어 있지 않습니다." },
    NoSystemsDetail { en: "The examples and every command work; there is nothing to run until systems are wired into zk-registry.", ko: "예제와 모든 명령은 됩니다. zk-registry에 시스템을 연결하기 전까지는 돌릴 것이 없습니다." },
    ListTitle { en: "Systems in this build: {count}", ko: "이 빌드의 시스템: {count}" },
    ShelfEmpty { en: "Nothing on the {shelf} shelf in this build.", ko: "이 빌드에는 {shelf} 선반에 아무것도 없습니다." },
    ListFooter { en: "/about <system> tells its story · /run <system> <example> runs it", ko: "/about <시스템> 이야기 보기 · /run <시스템> <예제> 돌리기" },
    ColId { en: "ID", ko: "ID" },
    ColName { en: "Name", ko: "이름" },
    ColYear { en: "Year", ko: "연도" },
    ColSetup { en: "Trusted setup", ko: "신뢰 설정" },
    ColZk { en: "Zero-knowledge", ko: "영지식" },
    ColProofSize { en: "Proof size", ko: "증명 크기" },
    ColCode { en: "Code", ko: "코드" },
    SetupNone { en: "none", ko: "없음" },
    SetupUniversal { en: "universal", ko: "범용" },
    SetupPerCircuit { en: "per circuit", ko: "회로마다" },
    SetupTrusted { en: "trusted component", ko: "믿어야 하는 부품" },
    ZkYes { en: "yes", ko: "예" },
    ZkNo { en: "no", ko: "아니오" },
    ZkOptional { en: "optional", ko: "선택" },
    AssumePairing { en: "pairings", ko: "페어링" },
    AssumeDiscreteLog { en: "discrete logarithm", ko: "이산 로그" },
    AssumeHash { en: "hash functions", ko: "해시 함수" },
    AssumeLattice { en: "lattices", ko: "격자" },
    AssumeTrusted { en: "a trusted component", ko: "믿어야 하는 부품" },
    SizeConstant { en: "constant", ko: "일정" },
    SizeLog { en: "logarithmic", ko: "로그" },
    SizePolylog { en: "polylogarithmic", ko: "다항 로그" },
    SizeSqrt { en: "square root", ko: "제곱근" },
    SizeLinear { en: "linear", ko: "선형" },
    RecNone { en: "none", ko: "없음" },
    RecRecursion { en: "recursion", ko: "재귀" },
    RecAccumulation { en: "accumulation", ko: "누적" },
    RecFolding { en: "folding", ko: "폴딩" },
    ModeNonInteractive { en: "non-interactive proof", ko: "비대화형 증명" },
    ModeInteractive { en: "live conversation", ko: "실시간 대화" },
    CodeUpstream { en: "upstream", ko: "원조" },
    CodeTeaching { en: "teaching", ko: "교육용" },
    CodeCompanion { en: "companion", ko: "동반" },
    CodeHomemade { en: "homemade", ko: "자작" },
    ImplUpstream { en: "{name} {version} ({license})", ko: "{name} {version} ({license})" },
    ImplTeaching { en: "teaching implementation · not audited, built on {crates}", ko: "교육용 구현 · 감사받지 않음 · 바탕: {crates}" },
    ImplCompanion { en: "companion executable nmtzk-{id}, running {upstream}", ko: "동반 실행 파일 nmtzk-{id} · 돌리는 코드: {upstream}" },
    ImplHomemade { en: "designed for this repository", ko: "이 저장소를 위해 설계함" },
    StatusActive { en: "in use", ko: "쓰이는 중" },
    StatusSuperseded { en: "superseded by {by} since {since}", ko: "대체됨 · {by} · {since}부터" },
    StatusDiscontinued { en: "discontinued since {since}", ko: "중단됨 · {since}부터" },
    StatusExperimental { en: "experimental", ko: "실험 중" },
    StatusHistorical { en: "historical", ko: "역사" },
    StatusAsOf { en: "{status} (as of {date})", ko: "{status} ({date} 기준)" },
    LabelAuthors { en: "Authors", ko: "저자" },
    LabelPaper { en: "Paper", ko: "논문" },
    LabelSetup { en: "Trusted setup", ko: "신뢰 설정" },
    LabelZk { en: "Zero-knowledge", ko: "영지식" },
    LabelAssumptions { en: "Assumptions", ko: "가정" },
    LabelPostQuantum { en: "Post-quantum", ko: "양자 내성" },
    LabelProofSize { en: "Proof size", ko: "증명 크기" },
    LabelRecursion { en: "Recursion", ko: "재귀" },
    LabelMode { en: "Mode", ko: "방식" },
    LabelField { en: "Field", ko: "필드" },
    LabelCode { en: "Code", ko: "코드" },
    LabelStatus { en: "Status", ko: "상태" },
    LabelUsedIn { en: "Used in", ko: "쓰이는 곳" },
    Yes { en: "yes", ko: "예" },
    No { en: "no", ko: "아니오" },
    PaperLine { en: "{title}, {venue}", ko: "{title}, {venue}" },
    DeploymentSince { en: "{project} (since {since})", ko: "{project} ({since}부터)" },
    DeploymentRange { en: "{project} ({since} to {until})", ko: "{project} ({since}~{until})" },
    AboutPage { en: "ctrl+o opens the page again.", ko: "ctrl+o로 페이지를 다시 엽니다." },
    AboutNoPage { en: "No page has been written for {system} yet.", ko: "아직 페이지를 쓰지 않았습니다 · {system}" },
    AboutNotBuilt { en: "{system} is not built into this binary; showing its page.", ko: "이 실행 파일에 들어 있지 않아 페이지만 보여 줍니다 · {system}" },
    CautionTeaching { en: "Teaching implementation · not audited", ko: "교육용 구현 · 감사받지 않음" },
    CautionHomemade { en: "Homemade · not audited", ko: "자작 · 감사받지 않음" },
    CautionNotZk { en: "Not zero-knowledge as run here: succinct is not the same as zero-knowledge.", ko: "여기서 돌리는 설정으로는 영지식이 아닙니다. 간결함과 영지식은 다른 성질입니다." },
    CautionOptionalZk { en: "Zero knowledge is optional in this system; its page says which setting runs here.", ko: "이 시스템에서 영지식은 선택입니다. 여기서 어느 설정을 돌리는지는 페이지에 적혀 있습니다." },
    CautionTrusted { en: "Trusted component: security rests on a part everyone must trust, not on mathematics.", ko: "믿어야 하는 부품: 안전성이 수학이 아니라 모두가 믿어야 하는 부분에 기댑니다." },
    ExamplesTitle { en: "Seven statements. Every system proves the same circuit.", ko: "문장 일곱. 모든 시스템이 같은 회로를 증명합니다." },
    ExamplesInputs { en: "public: {public} · private: {private}", ko: "공개: {public} · 비공개: {private}" },
    ExamplesMany { en: "{first} … {last} ({count} in all)", ko: "{first} … {last} (모두 {count})" },
    ExamplesToyHash { en: "Envelopes and digests use ToyHash, a toy for teaching and not a real hash.", ko: "봉투와 요약값은 ToyHash를 씁니다. 가르치기 위한 장난감이고 진짜 해시가 아닙니다." },
    ExOnePlusOne { en: "The answer sealed in this envelope is 1 + 1.", ko: "이 봉투에 봉인한 답은 1 + 1입니다." },
    ExPassword { en: "I know the PIN behind this digest.", ko: "나는 이 요약값 뒤의 PIN을 압니다." },
    ExSudoku { en: "I solved this 4×4 sudoku.", ko: "나는 이 4×4 스도쿠를 풀었습니다." },
    ExAge { en: "I am at least 18.", ko: "나는 18세 이상입니다." },
    ExMembership { en: "I am one of 16 members, without saying which.", ko: "나는 회원 16명 중 한 명입니다. 누구인지는 말하지 않습니다." },
    ExFactoring { en: "I know two factors of N, neither of them 1.", ko: "나는 N의 두 인수를 압니다. 둘 다 1이 아닙니다." },
    ExPoolSpend { en: "A spend in the Toy Shielded Pool.", ko: "장난감 비공개 송금의 지출 하나." },
    ExPoolSpendNoRangeChecks { en: "A pool spend with the range checks removed, to show a counterfeit getting through.", ko: "범위 확인을 뺀 송금 지출. 위조 동전이 통과하는 모습을 보여 줍니다." },
    ExPoolSpendUnboundNullifier { en: "A pool spend whose nullifier is not bound to the note, to show a double spend getting through.", ko: "널리파이어가 노트에 묶이지 않은 송금 지출. 이중 지출이 통과하는 모습을 보여 줍니다." },
}
