//! Words for Ali Baba's cave: the drawing's labels, each scene, the tapes and the court.

zk_i18n::messages! {
    TitleScenes { en: "Ali Baba's cave: {mode} · {example} · {scenes} scenes" },
    TitleFloors { en: "Ali Baba's cave: {mode} · {example} · {floors} floors" },
    ModeDemonstration { en: "the demonstration" },
    ModeImpostor { en: "the impostor" },
    ModeJealousEdit { en: "the jealous edit" },
    ModeCourt { en: "the court" },
    ModePriorAgreement { en: "prior agreement" },
    ModeApartment { en: "the apartment building" },
    DrawingDeadEnd { en: "dead end" },
    DrawingWall { en: "wall" },
    DrawingLeft { en: "left" },
    DrawingRight { en: "right" },
    DrawingFork { en: "fork" },
    DrawingEntrance { en: "entrance" },
    TrustInTheWall { en: "The trust is in the wall. In the story, too, the wall is magic." },
    IntroDemonstration { en: "Mick Ali goes in alone and walks down one passage. The reporter stops at the fork, flips a coin and calls the side Mick must come out on. Only the magic words open the wall." },
    IntroImpostor { en: "A double who looks like Mick goes in. The double does not know the words. The reporter follows the same steps as with Mick." },
    IntroJealousEdit { en: "A jealous reporter films the double, then cuts every take that went wrong until enough good scenes are left." },
    IntroCourt { en: "Mick's tape and the jealous reporter's edited tape go to court. The judge sees only the tapes and can only count what is on them." },
    IntroPriorAgreement { en: "The reporter and the double agree on every call before filming. No coin is flipped, and the double always waits in the passage that will be called." },
    IntroApartment { en: "Each floor of the building has its own cave and its own words. Mick is tested on every floor in the same round." },
    SceneLabel { en: "Scene {number}" },
    TakeLabel { en: "Take {number}" },
    FloorLabel { en: "Floor {number}" },
    CoinHeads { en: "heads" },
    CoinTails { en: "tails" },
    NoCoin { en: "no coin" },
    Called { en: "called {side}" },
    CameOut { en: "came out {side}" },
    SideLeft { en: "left" },
    SideRight { en: "right" },
    LetterLeft { en: "L" },
    LetterRight { en: "R" },
    WallNotNeeded { en: "wall not needed" },
    WallOpened { en: "wall opened" },
    WallStayedShut { en: "wall stayed shut" },
    WallNoWords { en: "no words for the wall" },
    Caught { en: "caught" },
    KeptAs { en: "kept as scene {number}" },
    Cut { en: "cut" },
    Stopped { en: "Stopped after {done} of {total}." },
    StoppedCounting { en: "Stopped before the averages were counted." },
    ReviewHeading { en: "After filming" },
    ReviewCalled { en: "called" },
    ReviewCameOut { en: "came out" },
    ReviewWentIn { en: "went in" },
    ReviewNotOnTape { en: "not on the tape: the camera stayed at the fork" },
    VerdictConvinced { en: "The reporter is convinced: all {scenes} scenes came out on the called side." },
    VerdictCaught { en: "Caught in scene {scene}: the double came out on the wrong side." },
    VerdictEscaped { en: "The double was not caught in {scenes} scenes." },
    VerdictAgreed { en: "The tape shows {scenes} good scenes, and nobody on it knows the words." },
    OddsExact { en: "Someone without the words gets through {scenes} scenes by luck with a chance of 1 in {odds}." },
    OddsApprox { en: "Someone without the words gets through {scenes} scenes by luck with a chance of about 1 in {odds}." },
    AgreedCalls { en: "Calls agreed before filming: {calls}" },
    EditSummary { en: "Takes filmed: {takes}. Kept: {kept}. Cut: {cut}." },
    EditExpected { en: "On average, {kept} good scenes take {expected} takes." },
    EditNote { en: "The edited tape shows every scene coming out on the called side, like Mick's tape." },
    TapeMick { en: "Mick's tape" },
    TapeEdited { en: "edited tape" },
    TapePair { en: "called {call}, came out {exit}" },
    CourtCounts { en: "What the judge can count" },
    CountScenes { en: "scenes" },
    CountRightCalls { en: "right calls" },
    CountLeftCalls { en: "left calls" },
    CountMatching { en: "came out on the called side" },
    CountRuns { en: "runs of the same call" },
    CountLongestRun { en: "longest run" },
    CourtAverages { en: "Averaged over {tapes} tapes of each kind" },
    AvgRightShare { en: "share of right calls" },
    AvgMatchShare { en: "share out on the called side" },
    AvgRuns { en: "runs per tape" },
    AvgLongestRun { en: "longest run per tape" },
    CourtChance { en: "One pair of tapes differs a little by chance. The averages show both kinds of tape come out the same." },
    CourtVerdict { en: "The judge cannot tell the tapes apart. The edited tape holds no words, so Mick's tape shows none either." },
    BuildingConvinced { en: "All {floors} floors came out on the called side in one round." },
    BuildingFailed { en: "Floors {floors} came out on the wrong side." },
    BuildingOdds { en: "Someone without the words passes all {floors} floors by luck with a chance of 1 in {odds}." },
    WorkingScene { en: "Scene {scene} of {total}" },
    WorkingTake { en: "Take {take}" },
    WorkingFloor { en: "Floor {floor} of {total}" },
    WorkingCourt { en: "Counting {tapes} tapes of each kind" },
    Failed { en: "The cave could not be filmed: {why}" },
}
