//! Words for Ali Baba's cave: the drawing's labels, each scene, the tapes and the court.

zk_i18n::messages! {
    TitleScenes { en: "Ali Baba's cave: {mode} · {example} · {scenes} scenes", ko: "알리바바의 동굴: {mode} · {example} · 장면 {scenes}" },
    TitleFloors { en: "Ali Baba's cave: {mode} · {example} · {floors} floors", ko: "알리바바의 동굴: {mode} · {example} · {floors}층" },
    ModeDemonstration { en: "the demonstration", ko: "시연" },
    ModeImpostor { en: "the impostor", ko: "닮은 배우" },
    ModeJealousEdit { en: "the jealous edit", ko: "질투하는 편집" },
    ModeCourt { en: "the court", ko: "법정" },
    ModePriorAgreement { en: "prior agreement", ko: "미리 짠 약속" },
    ModeApartment { en: "the apartment building", ko: "아파트" },
    DrawingDeadEnd { en: "dead end", ko: "막다른 곳" },
    DrawingWall { en: "wall", ko: "벽" },
    DrawingLeft { en: "left", ko: "왼쪽" },
    DrawingRight { en: "right", ko: "오른쪽" },
    DrawingFork { en: "fork", ko: "갈림길" },
    DrawingEntrance { en: "entrance", ko: "입구" },
    TrustInTheWall { en: "The trust is in the wall. In the story, too, the wall is magic.", ko: "믿음은 벽에 있습니다. 이야기에서도 벽은 마법입니다." },
    IntroDemonstration { en: "Mick Ali goes in alone and walks down one passage. The reporter stops at the fork, flips a coin and calls the side Mick must come out on. Only the magic words open the wall.", ko: "믹 알리가 혼자 들어가 한 길로 걸어갑니다. 기자는 갈림길에 멈춰 동전을 던지고, 믹이 나와야 할 쪽을 외칩니다. 벽은 주문으로만 열립니다." },
    IntroImpostor { en: "A double who looks like Mick goes in. The double does not know the words. The reporter follows the same steps as with Mick.", ko: "믹을 닮은 배우가 들어갑니다. 배우는 주문을 모릅니다. 기자는 믹 때와 똑같이 합니다." },
    IntroJealousEdit { en: "A jealous reporter films the double, then cuts every take that went wrong until enough good scenes are left.", ko: "질투하는 기자가 닮은 배우를 찍고, 좋은 장면이 충분히 남을 때까지 틀린 장면을 모두 잘라 냅니다." },
    IntroCourt { en: "Mick's tape and the jealous reporter's edited tape go to court. The judge sees only the tapes and can only count what is on them.", ko: "믹의 테이프와 질투하는 기자가 편집한 테이프가 법정에 갑니다. 판사는 테이프만 보고, 테이프에 있는 것만 셀 수 있습니다." },
    IntroPriorAgreement { en: "The reporter and the double agree on every call before filming. No coin is flipped, and the double always waits in the passage that will be called.", ko: "기자와 닮은 배우가 촬영 전에 외칠 쪽을 모두 짭니다. 동전은 던지지 않고, 배우는 늘 외칠 쪽 길에서 기다립니다." },
    IntroApartment { en: "Each floor of the building has its own cave and its own words. Mick is tested on every floor in the same round.", ko: "건물의 층마다 자기 동굴과 자기 주문이 있습니다. 믹은 한 라운드에 모든 층에서 시험받습니다." },
    SceneLabel { en: "Scene {number}", ko: "장면 {number}" },
    TakeLabel { en: "Take {number}", ko: "테이크 {number}" },
    FloorLabel { en: "Floor {number}", ko: "{number}층" },
    CoinHeads { en: "heads", ko: "앞면" },
    CoinTails { en: "tails", ko: "뒷면" },
    NoCoin { en: "no coin", ko: "동전 없음" },
    Called { en: "called {side}", ko: "외침 {side}" },
    CameOut { en: "came out {side}", ko: "나옴 {side}" },
    SideLeft { en: "left", ko: "왼쪽" },
    SideRight { en: "right", ko: "오른쪽" },
    LetterLeft { en: "L", ko: "왼" },
    LetterRight { en: "R", ko: "오" },
    WallNotNeeded { en: "wall not needed", ko: "벽 필요 없음" },
    WallOpened { en: "wall opened", ko: "벽 열림" },
    WallStayedShut { en: "wall stayed shut", ko: "벽 닫힌 채" },
    WallNoWords { en: "no words for the wall", ko: "벽을 열 주문 없음" },
    Caught { en: "caught", ko: "들킴" },
    KeptAs { en: "kept as scene {number}", ko: "남김 · 장면 {number}" },
    Cut { en: "cut", ko: "잘라 냄" },
    Stopped { en: "Stopped after {done} of {total}.", ko: "{total} 중 {done}에서 멈췄습니다." },
    StoppedCounting { en: "Stopped before the averages were counted.", ko: "평균을 세기 전에 멈췄습니다." },
    ReviewHeading { en: "After filming", ko: "촬영 뒤" },
    ReviewCalled { en: "called", ko: "외친 쪽" },
    ReviewCameOut { en: "came out", ko: "나온 쪽" },
    ReviewWentIn { en: "went in", ko: "들어간 쪽" },
    ReviewNotOnTape { en: "not on the tape: the camera stayed at the fork", ko: "테이프에 없음: 카메라는 갈림길에 있었습니다" },
    VerdictConvinced { en: "The reporter is convinced: all {scenes} scenes came out on the called side.", ko: "기자가 납득했습니다: 장면 {scenes}개 모두 외친 쪽으로 나왔습니다." },
    VerdictCaught { en: "Caught in scene {scene}: the double came out on the wrong side.", ko: "장면 {scene}에서 들켰습니다: 닮은 배우가 틀린 쪽으로 나왔습니다." },
    VerdictEscaped { en: "The double was not caught in {scenes} scenes.", ko: "장면 {scenes}개 동안 닮은 배우가 들키지 않았습니다." },
    VerdictAgreed { en: "The tape shows {scenes} good scenes, and nobody on it knows the words.", ko: "테이프에는 좋은 장면이 {scenes}개 있고, 테이프 속 누구도 주문을 모릅니다." },
    OddsExact { en: "Someone without the words gets through {scenes} scenes by luck with a chance of 1 in {odds}.", ko: "주문을 모르는 사람이 운으로 장면 {scenes}개를 통과할 확률: {odds}분의 1." },
    OddsApprox { en: "Someone without the words gets through {scenes} scenes by luck with a chance of about 1 in {odds}.", ko: "주문을 모르는 사람이 운으로 장면 {scenes}개를 통과할 확률: 약 {odds}분의 1." },
    AgreedCalls { en: "Calls agreed before filming: {calls}", ko: "촬영 전에 짠 외침: {calls}" },
    EditSummary { en: "Takes filmed: {takes}. Kept: {kept}. Cut: {cut}.", ko: "찍은 테이크: {takes}. 남김: {kept}. 잘라 냄: {cut}." },
    EditExpected { en: "On average, {kept} good scenes take {expected} takes.", ko: "좋은 장면 {kept}개를 얻는 데 평균 {expected}테이크가 듭니다." },
    EditNote { en: "The edited tape shows every scene coming out on the called side, like Mick's tape.", ko: "편집한 테이프도 믹의 테이프처럼 모든 장면에서 외친 쪽으로 나옵니다." },
    TapeMick { en: "Mick's tape", ko: "믹의 테이프" },
    TapeEdited { en: "edited tape", ko: "편집한 테이프" },
    TapePair { en: "called {call}, came out {exit}", ko: "외침 {call}, 나옴 {exit}" },
    CourtCounts { en: "What the judge can count", ko: "판사가 셀 수 있는 것" },
    CountScenes { en: "scenes", ko: "장면" },
    CountRightCalls { en: "right calls", ko: "오른쪽 외침" },
    CountLeftCalls { en: "left calls", ko: "왼쪽 외침" },
    CountMatching { en: "came out on the called side", ko: "외친 쪽으로 나옴" },
    CountRuns { en: "runs of the same call", ko: "같은 외침이 이어진 구간" },
    CountLongestRun { en: "longest run", ko: "가장 긴 구간" },
    CourtAverages { en: "Averaged over {tapes} tapes of each kind", ko: "종류마다 테이프 {tapes}개의 평균" },
    AvgRightShare { en: "share of right calls", ko: "오른쪽 외침의 비율" },
    AvgMatchShare { en: "share out on the called side", ko: "외친 쪽으로 나온 비율" },
    AvgRuns { en: "runs per tape", ko: "테이프마다 구간 수" },
    AvgLongestRun { en: "longest run per tape", ko: "테이프마다 가장 긴 구간" },
    CourtChance { en: "One pair of tapes differs a little by chance. The averages show both kinds of tape come out the same.", ko: "테이프 한 쌍은 우연히 조금 다릅니다. 평균을 보면 두 종류의 테이프가 똑같이 나옵니다." },
    CourtVerdict { en: "The judge cannot tell the tapes apart. The edited tape holds no words, so Mick's tape shows none either.", ko: "판사는 두 테이프를 구별하지 못합니다. 편집한 테이프에는 주문이 없으니, 믹의 테이프도 주문을 보여 주지 않습니다." },
    BuildingConvinced { en: "All {floors} floors came out on the called side in one round.", ko: "한 라운드에 {floors}개 층 모두 외친 쪽으로 나왔습니다." },
    BuildingFailed { en: "Floors {floors} came out on the wrong side.", ko: "틀린 쪽으로 나온 층: {floors}" },
    BuildingOdds { en: "Someone without the words passes all {floors} floors by luck with a chance of 1 in {odds}.", ko: "주문을 모르는 사람이 운으로 {floors}개 층을 모두 통과할 확률: {odds}분의 1." },
    WorkingScene { en: "Scene {scene} of {total}", ko: "장면 {scene} / {total}" },
    WorkingTake { en: "Take {take}", ko: "테이크 {take}" },
    WorkingFloor { en: "Floor {floor} of {total}", ko: "{floor}층 / {total}" },
    WorkingCourt { en: "Counting {tapes} tapes of each kind", ko: "종류마다 테이프 {tapes}개 세는 중" },
    Failed { en: "The cave could not be filmed: {why}", ko: "동굴을 찍지 못했습니다: {why}" },
}
