//! Words for the trusted-setup ceremony: toxic waste, Powers of Tau and the colluders.

zk_i18n::messages! {
    Subject { en: "the trusted-setup ceremony", ko: "신뢰 설정 의식" },
    TitleToxic { en: "Trusted setup: toxic waste", ko: "신뢰 설정: 독성 폐기물" },
    TitleTau { en: "Trusted setup: Powers of Tau · {participants} participants", ko: "신뢰 설정: Powers of Tau · 참여자 {participants}명" },
    TitleCollude { en: "Trusted setup: when every participant keeps the secret · {participants} participants", ko: "신뢰 설정: 모든 참여자가 비밀을 간직할 때 · 참여자 {participants}명" },
    IntroToxic { en: "Groth16 keys are made from five secret numbers. Here they are kept on purpose, to show what a copy of them is worth.", ko: "Groth16 키는 비밀 수 다섯 개로 만듭니다. 여기서는 그 사본이 무슨 가치가 있는지 보여 주려고 일부러 간직합니다." },
    IntroTau { en: "Each participant multiplies a secret of their own into the reference string, then throws the secret away. Anyone can check every turn. If even one participant threw the secret away, nobody knows the final τ.", ko: "참여자마다 자기 비밀을 참조 문자열에 곱해 넣고, 그 비밀을 버립니다. 누구든 차례마다 확인할 수 있습니다. 한 명이라도 비밀을 버렸다면 마지막 τ를 아는 사람은 없습니다." },
    IntroCollude { en: "This time every participant keeps their secret. Together those secrets make the final τ.", ko: "이번에는 모든 참여자가 비밀을 간직합니다. 그 비밀들을 합치면 마지막 τ가 됩니다." },
    ToxicKeys { en: "bellman's own key generator made Groth16 keys for one-plus-one from α, β, γ, δ and τ, all kept.", ko: "bellman 자체의 키 생성기가 α, β, γ, δ, τ로 one-plus-one용 Groth16 키를 만들었고, 다섯 수를 모두 간직했습니다." },
    ToxicClaim { en: "The false claim: the sealed envelope holds 3. No witness for it exists.", ko: "거짓 주장: 봉인한 봉투에 3이 들어 있다. 이 주장의 증인은 없습니다." },
    ToxicForged { en: "A proof forged from β, γ and δ alone, with no witness:", ko: "증인 없이 β, γ, δ만으로 위조한 증명:" },
    ToxicPoint { en: "{name} {bytes}", ko: "{name} {bytes}" },
    ToxicAccepted { en: "The ordinary Groth16 verifier accepts the forged proof.", ko: "평범한 Groth16 검증자가 위조한 증명을 받아들입니다." },
    ToxicNotAccepted { en: "The ordinary Groth16 verifier rejected the forged proof, which the design says it accepts.", ko: "평범한 Groth16 검증자가 위조한 증명을 거절했습니다. 설계대로라면 받아들여야 합니다." },
    ToxicGuessRejected { en: "The same forgery with a guessed δ is rejected.", ko: "δ를 추측해서 같은 위조를 하면 거절됩니다." },
    ToxicGuessAccepted { en: "The same forgery with a guessed δ was accepted, which the design says cannot happen.", ko: "δ를 추측한 같은 위조가 받아들여졌습니다. 설계상 일어날 수 없는 일입니다." },
    ToxicLesson { en: "Whoever keeps these numbers can prove anything, so a setup has to forget them. Without β, γ and δ there is no way to compute the forged part C.", ko: "이 수들을 간직한 사람은 무엇이든 증명할 수 있으므로, 설정은 이 수들을 잊어야 합니다. β, γ, δ 없이는 위조 부분 C를 계산할 방법이 없습니다." },
    TauStart { en: "The string starts at τ = 1, which everyone knows · fingerprint {fingerprint}", ko: "문자열은 모두가 아는 τ = 1에서 시작합니다 · 지문 {fingerprint}" },
    TurnDiscarded { en: "Participant {number} multiplied in a secret and did not keep it · fingerprint {fingerprint}", ko: "참여자 {number}: 비밀을 곱해 넣고 간직하지 않았습니다 · 지문 {fingerprint}" },
    TurnKept { en: "Participant {number} multiplied in a secret and kept it · fingerprint {fingerprint}", ko: "참여자 {number}: 비밀을 곱해 넣고 간직했습니다 · 지문 {fingerprint}" },
    CheckedTurn { en: "Turn {number}:", ko: "차례 {number}:" },
    CheckWellFormed { en: "shape", ko: "모양" },
    CheckKnowledgeProof { en: "knowledge proof", ko: "지식 증명" },
    CheckSameSecret { en: "same secret in G1 and G2", ko: "G1과 G2에 같은 비밀" },
    CheckBuildsOnPrevious { en: "builds on the previous string", ko: "앞 문자열 위에 쌓음" },
    CheckConsistentPowers { en: "consistent powers", ko: "거듭제곱이 일관됨" },
    ChainVerified { en: "Every turn checks out. The final τ is a product of {participants} secrets that nobody kept.", ko: "모든 차례가 확인됐습니다. 마지막 τ는 아무도 간직하지 않은 비밀 {participants}개의 곱입니다." },
    ChainRejected { en: "The whole chain did not check out.", ko: "사슬 전체가 확인되지 않았습니다." },
    CheatIgnored { en: "Participant {number} ignores every earlier turn and starts from a τ of their own.", ko: "참여자 {number}: 앞선 차례를 모두 무시하고 자기 τ에서 시작합니다." },
    CheatReplaced { en: "Participant {number} takes an honest turn, then swaps power {power} for a random point.", ko: "참여자 {number}: 정직하게 차례를 마친 뒤, 거듭제곱 하나(번호 {power})를 무작위 점으로 바꿔치기합니다." },
    CaughtBy { en: "Caught by the check: {check}.", ko: "잡은 확인: {check}." },
    NotCaught { en: "Not caught by any check.", ko: "어떤 확인에도 잡히지 않았습니다." },
    HonestOpening { en: "A commitment to p(X) = 3 + X + 4X^2 + X^3 + 5X^4 over the final string, opened honestly at X = {point}: p({point}) = {value}. The KZG verifier accepts.", ko: "마지막 문자열 위에서 p(X) = 3 + X + 4X^2 + X^3 + 5X^4에 약속하고, X = {point}에서 정직하게 엽니다: p({point}) = {value}. KZG 검증자가 받아들입니다." },
    HonestOpeningRejected { en: "The honest opening of p(X) at X = {point} was rejected.", ko: "X = {point}에서 p(X)의 정직한 열기가 거절됐습니다." },
    ForgedAll { en: "With all {kept} secrets, the colluders open the commitment to p({point}) = {claimed}. The ordinary KZG verifier accepts it.", ko: "비밀 {kept}개를 모두 가진 담합자들이 약속을 p({point}) = {claimed}로 엽니다. 평범한 KZG 검증자가 받아들입니다." },
    ForgedAllRejected { en: "With all {kept} secrets, the forged opening to p({point}) = {claimed} was rejected, which the design says cannot happen.", ko: "비밀 {kept}개를 모두 가지고도 p({point}) = {claimed}로 위조한 열기가 거절됐습니다. 설계상 일어날 수 없는 일입니다." },
    ForgedMissing { en: "With {kept} of {total} secrets, the same forgery is rejected.", ko: "비밀 {total}개 중 {kept}개로는 같은 위조가 거절됩니다." },
    ForgedMissingAccepted { en: "With {kept} of {total} secrets, the forgery was accepted, which the design says cannot happen.", ko: "비밀 {total}개 중 {kept}개로 위조가 받아들여졌습니다. 설계상 일어날 수 없는 일입니다." },
    ColludeLesson { en: "One participant who throws the secret away is enough to stop this.", ko: "비밀을 버리는 참여자 한 명이면 이것을 막기에 충분합니다." },
    Unexpected { en: "The ceremony did not come out the way its design says it must. This is a fault in the program.", ko: "의식이 설계대로 나오지 않았습니다. 프로그램의 결함입니다." },
    Stopped { en: "Stopped after {done} of {total} steps.", ko: "{total}단계 중 {done}단계 뒤에 멈췄습니다." },
    WorkingKeys { en: "Making keys from known toxic waste", ko: "알려진 독성 폐기물로 키 만드는 중" },
    WorkingClaim { en: "Writing the false claim", ko: "거짓 주장 쓰는 중" },
    WorkingForge { en: "Forging a proof", ko: "증명 위조 중" },
    WorkingGuess { en: "Forging again with a guessed δ", ko: "δ를 추측해 다시 위조하는 중" },
    WorkingTurn { en: "Participant {number} of {total}", ko: "참여자 {number} / {total}" },
    WorkingCheck { en: "Checking turn {number} of {total}", ko: "차례 {number} / {total} 확인 중" },
    WorkingCheat { en: "A cheating participant", ko: "속이는 참여자" },
    WorkingOpen { en: "Opening the commitment", ko: "약속 여는 중" },
    WorkingForgeOpening { en: "Forging an opening", ko: "열기 위조 중" },
    Failed { en: "The ceremony could not run: {why}", ko: "의식을 진행하지 못했습니다: {why}" },
}
