//! Words for the trusted-setup ceremony: toxic waste, Powers of Tau and the colluders.

zk_i18n::messages! {
    Subject { en: "the trusted-setup ceremony" },
    TitleToxic { en: "Trusted setup: toxic waste" },
    TitleTau { en: "Trusted setup: Powers of Tau · {participants} participants" },
    TitleCollude { en: "Trusted setup: when every participant keeps the secret · {participants} participants" },
    IntroToxic { en: "Groth16 keys are made from five secret numbers. Here they are kept on purpose, to show what a copy of them is worth." },
    IntroTau { en: "Each participant multiplies a secret of their own into the reference string, then throws the secret away. Anyone can check every turn. If even one participant threw the secret away, nobody knows the final τ." },
    IntroCollude { en: "This time every participant keeps their secret. Together those secrets make the final τ." },
    ToxicKeys { en: "bellman's own key generator made Groth16 keys for one-plus-one from α, β, γ, δ and τ, all kept." },
    ToxicClaim { en: "The false claim: the sealed envelope holds 3. No witness for it exists." },
    ToxicForged { en: "A proof forged from β, γ and δ alone, with no witness:" },
    ToxicPoint { en: "{name} {bytes}" },
    ToxicAccepted { en: "The ordinary Groth16 verifier accepts the forged proof." },
    ToxicNotAccepted { en: "The ordinary Groth16 verifier rejected the forged proof, which the design says it accepts." },
    ToxicGuessRejected { en: "The same forgery with a guessed δ is rejected." },
    ToxicGuessAccepted { en: "The same forgery with a guessed δ was accepted, which the design says cannot happen." },
    ToxicLesson { en: "Whoever keeps these numbers can prove anything, so a setup has to forget them. Without β, γ and δ there is no way to compute the forged part C." },
    TauStart { en: "The string starts at τ = 1, which everyone knows · fingerprint {fingerprint}" },
    TurnDiscarded { en: "Participant {number} multiplied in a secret and did not keep it · fingerprint {fingerprint}" },
    TurnKept { en: "Participant {number} multiplied in a secret and kept it · fingerprint {fingerprint}" },
    CheckedTurn { en: "Turn {number}:" },
    CheckWellFormed { en: "shape" },
    CheckKnowledgeProof { en: "knowledge proof" },
    CheckSameSecret { en: "same secret in G1 and G2" },
    CheckBuildsOnPrevious { en: "builds on the previous string" },
    CheckConsistentPowers { en: "consistent powers" },
    ChainVerified { en: "Every turn checks out. The final τ is a product of {participants} secrets that nobody kept." },
    ChainRejected { en: "The whole chain did not check out." },
    CheatIgnored { en: "Participant {number} ignores every earlier turn and starts from a τ of their own." },
    CheatReplaced { en: "Participant {number} takes an honest turn, then swaps power {power} for a random point." },
    CaughtBy { en: "Caught by the check: {check}." },
    NotCaught { en: "Not caught by any check." },
    HonestOpening { en: "A commitment to p(X) = 3 + X + 4X^2 + X^3 + 5X^4 over the final string, opened honestly at X = {point}: p({point}) = {value}. The KZG verifier accepts." },
    HonestOpeningRejected { en: "The honest opening of p(X) at X = {point} was rejected." },
    ForgedAll { en: "With all {kept} secrets, the colluders open the commitment to p({point}) = {claimed}. The ordinary KZG verifier accepts it." },
    ForgedAllRejected { en: "With all {kept} secrets, the forged opening to p({point}) = {claimed} was rejected, which the design says cannot happen." },
    ForgedMissing { en: "With {kept} of {total} secrets, the same forgery is rejected." },
    ForgedMissingAccepted { en: "With {kept} of {total} secrets, the forgery was accepted, which the design says cannot happen." },
    ColludeLesson { en: "One participant who throws the secret away is enough to stop this." },
    Unexpected { en: "The ceremony did not come out the way its design says it must. This is a fault in the program." },
    Stopped { en: "Stopped after {done} of {total} steps." },
    WorkingKeys { en: "Making keys from known toxic waste" },
    WorkingClaim { en: "Writing the false claim" },
    WorkingForge { en: "Forging a proof" },
    WorkingGuess { en: "Forging again with a guessed δ" },
    WorkingTurn { en: "Participant {number} of {total}" },
    WorkingCheck { en: "Checking turn {number} of {total}" },
    WorkingCheat { en: "A cheating participant" },
    WorkingOpen { en: "Opening the commitment" },
    WorkingForgeOpening { en: "Forging an opening" },
    Failed { en: "The ceremony could not run: {why}" },
}
