//! Words for the Toy Shielded Pool: actions, receipts, the ledger, wallets and attacks.

zk_i18n::messages! {
    Subject { en: "the Toy Shielded Pool", ko: "장난감 비공개 송금" },
    Disclaimer { en: "Toy Shielded Pool: an unofficial toy after Zcash's Sapling and Orchard designs, not affiliated with Zcash. No network, no real value.", ko: "장난감 비공개 송금: Zcash의 Sapling·Orchard 설계를 본뜬 비공식 장난감이며 Zcash와 무관합니다. 네트워크도, 실제 가치도 없습니다." },
    HelpTitle { en: "Toy Shielded Pool", ko: "장난감 비공개 송금" },
    HelpUse { en: "prove with Groth16, as Sapling does, or Halo 2, as Orchard does", ko: "Sapling처럼 Groth16으로, 또는 Orchard처럼 Halo 2로 증명하기" },
    HelpWalletNew { en: "create a wallet: a spending key and its address", ko: "지갑 만들기: 지출 키와 그 주소" },
    HelpWallet { en: "what only this wallet's owner sees", ko: "이 지갑 주인만 보는 것" },
    HelpWallets { en: "every wallet with its balances", ko: "모든 지갑과 잔액" },
    HelpFaucet { en: "give a wallet transparent coins, in the open", ko: "지갑에 투명 코인을 공개적으로 주기" },
    HelpShield { en: "move transparent coins into a shielded note", ko: "투명 코인을 가린 노트로 옮기기" },
    HelpSend { en: "pay from one wallet's note to another wallet", ko: "한 지갑의 노트에서 다른 지갑으로 지불하기" },
    HelpUnshield { en: "take coins out of a note, back into the open", ko: "노트에서 코인을 꺼내 공개로 돌려놓기" },
    HelpLedger { en: "what the world sees", ko: "세상이 보는 것" },
    HelpAttack { en: "try to break the pool, in scratch pools", ko: "임시 풀에서 이 풀을 깨 보기" },
    HelpReset { en: "delete this system's ledger and wallets", ko: "이 시스템의 원장과 지갑 지우기" },
    NoDataDir { en: "There is no directory to keep the pool in. Set HOME or pass --data-dir.", ko: "풀을 둘 디렉터리가 없습니다. HOME을 설정하거나 --data-dir을 주세요." },
    ConfirmReset { en: "This deletes the {system} pool's ledger and every wallet in it. Type /pool reset --yes, or run nmtzk pool reset --yes, to go ahead.", ko: "{system} 풀의 원장과 그 안의 모든 지갑을 지웁니다. 진행하려면 /pool reset --yes를 치거나 nmtzk pool reset --yes를 실행하세요." },
    ResetPrompt { en: "Delete the {system} pool's ledger and every wallet in it? Type yes to go ahead:", ko: "{system} 풀의 원장과 그 안의 모든 지갑을 지울까요? 진행하려면 yes를 치세요:" },
    ResetKept { en: "Nothing was deleted.", ko: "아무것도 지우지 않았습니다." },
    ResetDone { en: "The {system} pool is empty again.", ko: "{system} 풀이 다시 비었습니다." },
    Chosen { en: "The pool now proves with {system}. Each proof system keeps its own ledger and wallets.", ko: "이제 풀이 이 시스템으로 증명합니다: {system}. 증명 시스템마다 원장과 지갑을 따로 둡니다." },
    ChosenDir { en: "Kept in {dir}", ko: "보관 위치: {dir}" },
    Stopped { en: "Stopped before the ledger decided. Nothing was recorded.", ko: "원장이 결정하기 전에 멈췄습니다. 아무것도 기록되지 않았습니다." },
    ErrInvalidName { en: "'{name}' cannot be a wallet name. Use 1 to 32 of a–z, 0–9, - and _.", ko: "지갑 이름으로 쓸 수 없습니다: '{name}'. a–z, 0–9, -, _ 중에서 1~32자를 쓰세요." },
    ErrWalletExists { en: "A wallet named {name} already exists.", ko: "같은 이름의 지갑이 이미 있습니다: {name}" },
    ErrUnknownWallet { en: "No wallet is named {name}. /pool wallets lists them.", ko: "그런 이름의 지갑이 없습니다: {name}. /pool wallets가 목록을 보여 줍니다." },
    ErrZeroAmount { en: "The amount must be at least 1.", ko: "금액은 1 이상이어야 합니다." },
    ErrNotEnoughTransparent { en: "{name} has {balance} transparent coins and cannot shield {amount}.", ko: "투명 코인이 모자랍니다: {name} 잔액 {balance}, 가리려는 금액 {amount}." },
    ErrNoNoteLargeEnough { en: "{name} has no single note of at least {amount}. The largest holds {largest}, and a spend uses one note.", ko: "{amount} 이상인 노트가 없습니다: {name}. 가장 큰 노트는 {largest}이고, 지출 하나는 노트 하나를 씁니다." },
    ErrStorage { en: "The pool's files could not be read or written: {why}", ko: "풀의 파일을 읽거나 쓰지 못했습니다: {why}" },
    ErrCorrupt { en: "The pool's files do not describe a valid pool: {why}", ko: "풀의 파일이 올바른 풀을 담고 있지 않습니다: {why}" },
    ErrMismatch { en: "This ledger belongs to {found}, not to {expected}.", ko: "이 원장의 증명 시스템이 다릅니다: 기대 {expected}, 실제 {found}." },
    ErrCircuit { en: "The spend circuit failed: {why}", ko: "지출 회로가 실패했습니다: {why}" },
    ErrRandomness { en: "The operating system gave no randomness: {why}", ko: "운영체제가 난수를 주지 않았습니다: {why}" },
    ErrSystem { en: "The proof system failed: {why}", ko: "증명 시스템이 실패했습니다: {why}" },
    ProvingShield { en: "{name} shields {amount} with {system}", ko: "가리기 · {name} · {amount} · {system}" },
    ProvingSend { en: "{from} sends {amount} to {to} with {system}", ko: "비공개 송금 · {from} → {to} · {amount} · {system}" },
    ProvingUnshield { en: "{name} unshields {amount} with {system}", ko: "드러내기 · {name} · {amount} · {system}" },
    ProvingAttack { en: "Attack: {attack}, with {system}", ko: "공격 · {attack} · {system}" },
    WorkingProve { en: "Proving with {system}; the first proof also builds its keys", ko: "증명 중 · {system} · 첫 증명은 키도 만듭니다" },
    ReceiptNewWallet { en: "{name} has a new wallet", ko: "새 지갑: {name}" },
    ReceiptFaucet { en: "The faucet gave {name} {amount} transparent coins · transaction {index}", ko: "파우셋 · {name}에게 투명 코인 {amount} · 트랜잭션 {index}" },
    ReceiptShield { en: "{name} shielded {amount} · transaction {index}", ko: "가리기 · {name} · {amount} · 트랜잭션 {index}" },
    ReceiptSend { en: "{from} sent {amount} to {to} · transaction {index}", ko: "비공개 송금 · {from} → {to} · {amount} · 트랜잭션 {index}" },
    ReceiptUnshield { en: "{name} unshielded {amount} · transaction {index}", ko: "드러내기 · {name} · {amount} · 트랜잭션 {index}" },
    ReceiptRefused { en: "The ledger refused this transaction. Nothing was recorded.", ko: "원장이 이 트랜잭션을 거절했습니다. 아무것도 기록되지 않았습니다." },
    WorldHeading { en: "What the world sees", ko: "세상이 보는 것" },
    WorldNothing { en: "nothing: a new key never reaches the ledger", ko: "없음: 새 키는 원장에 닿지 않습니다" },
    OwnerHeading { en: "What only the wallets see", ko: "지갑만 보는 것" },
    OwnerNothing { en: "nothing: a faucet happens in the open", ko: "없음: 파우셋은 공개적으로 일어납니다" },
    FieldKind { en: "kind", ko: "종류" },
    FieldTransparent { en: "transparent", ko: "투명" },
    FieldAnchor { en: "anchor", ko: "앵커" },
    FieldNullifier { en: "nullifier", ko: "널리파이어" },
    FieldCommitments { en: "new note commitments", ko: "새 노트 약속" },
    FieldValue { en: "public value", ko: "공개 금액" },
    FieldProof { en: "proof", ko: "증명" },
    FieldTiming { en: "time", ko: "시간" },
    FieldPositions { en: "tree positions", ko: "트리 위치" },
    FieldAddress { en: "address", ko: "주소" },
    FieldKey { en: "spending key", ko: "지출 키" },
    FieldInput { en: "spent note", ko: "쓴 노트" },
    FieldOutput { en: "note {number}", ko: "노트 {number}" },
    KindFaucet { en: "faucet", ko: "파우셋" },
    KindShield { en: "shield", ko: "가리기" },
    KindShieldedTransfer { en: "shielded transfer", ko: "비공개 송금" },
    KindUnshield { en: "unshield", ko: "드러내기" },
    TransparentCredit { en: "{account} receives {amount}", ko: "받음 · {account} · {amount}" },
    TransparentDebit { en: "{account} pays {amount}", ko: "냄 · {account} · {amount}" },
    ValueInOut { en: "{in} in, {out} out", ko: "들어옴 {in}, 나감 {out}" },
    Timing { en: "proved in {prove}, verified in {verify}", ko: "증명 {prove}, 검증 {verify}" },
    KeyKept { en: "stays in {name}'s wallet file", ko: "{name}의 지갑 파일에 남습니다" },
    InputDummy { en: "a zero-value note under a throwaway key: a shield spends no note", ko: "버리는 키로 만든 금액 0 노트: 가리기는 노트를 쓰지 않습니다" },
    InputNote { en: "{owner}'s note of {value} at position {position}", ko: "{owner}의 노트 · 금액 {value} · 위치 {position}" },
    InputNoteOtherKey { en: "{owner}'s note of {value} at position {position}, spent with {holder}'s key", ko: "{owner}의 노트 · 금액 {value} · 위치 {position} · 쓴 키: {holder}" },
    OutputTo { en: "{value} to {recipient}", ko: "{value} → {recipient}" },
    OutputNobody { en: "{value} to an address nobody holds", ko: "{value} → 아무도 갖지 않은 주소" },
    OutputPosition { en: "position {position}", ko: "위치 {position}" },
    DeliveryHanded { en: "handed to the wallet file on this machine", ko: "이 기계의 지갑 파일에 전달함" },
    DeliveryDiscarded { en: "kept by nobody", ko: "아무도 보관하지 않음" },
    VerifierAccepted { en: "{system}'s verifier accepts the proof.", ko: "{system} 검증자가 증명을 받아들입니다." },
    VerifierRejected { en: "{system}'s verifier rejects the proof.", ko: "{system} 검증자가 증명을 거절합니다." },
    VerifierMalformed { en: "{system}'s verifier could not read the proof: {why}", ko: "{system} 검증자가 증명을 읽지 못했습니다: {why}" },
    RulesHeading { en: "Rules the ledger applied", ko: "원장이 적용한 규칙" },
    RuleProof { en: "the proof verifies", ko: "증명이 검증됨" },
    RuleRoot { en: "the anchor is a root the ledger has had", ko: "앵커가 원장에 있었던 루트임" },
    RuleNullifier { en: "the nullifier was not published before", ko: "널리파이어가 전에 공개된 적 없음" },
    RuleFunds { en: "the transparent account can pay what goes in", ko: "투명 계정이 들어갈 금액을 낼 수 있음" },
    RuleTurnstile { en: "the value in the pool stays at zero or above: {before} → {after}", ko: "풀 안의 금액이 0 이상으로 남음: {before} → {after}" },
    RuleTree { en: "the tree has room for two more notes", ko: "트리에 노트 두 개가 더 들어갈 자리가 있음" },
    KeysBuilt { en: "{system} keys were built first, in {time}.", ko: "{system} 키를 먼저 만들었습니다: {time}." },
    LedgerTitle { en: "The ledger · {system} · what the world sees", ko: "원장 · {system} · 세상이 보는 것" },
    LedgerCircuit { en: "circuit", ko: "회로" },
    LedgerPoolValue { en: "value in the pool", ko: "풀 안의 금액" },
    LedgerTree { en: "notes in the tree", ko: "트리의 노트" },
    LedgerTreeValue { en: "{used} of {capacity}", ko: "{capacity} 중 {used}" },
    LedgerRoot { en: "root", ko: "루트" },
    LedgerNullifiers { en: "nullifiers published", ko: "공개된 널리파이어" },
    LedgerTransparent { en: "transparent balances", ko: "투명 잔액" },
    LedgerNone { en: "none", ko: "없음" },
    LedgerEmpty { en: "No transactions yet.", ko: "아직 트랜잭션이 없습니다." },
    ColIndex { en: "#", ko: "#" },
    ColKind { en: "Kind", ko: "종류" },
    ColTransparent { en: "Transparent", ko: "투명" },
    ColNullifier { en: "Nullifier", ko: "널리파이어" },
    ColNotes { en: "New notes", ko: "새 노트" },
    ColProof { en: "Proof", ko: "증명" },
    WalletTitle { en: "Wallet {name} · {system} · what only {name} sees", ko: "지갑 {name} · {system} · 이 지갑 주인만 보는 것" },
    WalletShielded { en: "shielded balance", ko: "가린 잔액" },
    WalletTransparent { en: "transparent balance", ko: "투명 잔액" },
    WalletTransparentPublic { en: "public: the ledger shows it", ko: "공개: 원장에 보입니다" },
    WalletNoNotes { en: "No notes yet.", ko: "아직 노트가 없습니다." },
    ColNote { en: "Note", ko: "노트" },
    ColValue { en: "Value", ko: "금액" },
    ColPosition { en: "Position", ko: "위치" },
    ColReceived { en: "From tx", ko: "받은 트랜잭션" },
    ColState { en: "State", ko: "상태" },
    ColCommitment { en: "Commitment", ko: "약속" },
    StateSpent { en: "spent", ko: "씀" },
    StateUnspent { en: "unspent", ko: "안 씀" },
    WalletsTitle { en: "Wallets · {system}", ko: "지갑 · {system}" },
    WalletsEmpty { en: "No wallets yet. /pool wallet new <name> creates one.", ko: "아직 지갑이 없습니다. /pool wallet new <이름>으로 만듭니다." },
    ColName { en: "Name", ko: "이름" },
    ColShielded { en: "Shielded", ko: "가린 잔액" },
    ColNoteCount { en: "Notes", ko: "노트" },
    AttackTitle { en: "Attack: {attack} · {system}", ko: "공격: {attack} · {system}" },
    AttackDoubleSpend { en: "double spend", ko: "이중 지불" },
    AttackSteal { en: "steal", ko: "훔치기" },
    AttackCounterfeit { en: "counterfeit", ko: "위조" },
    AttackUnboundNullifier { en: "unbound nullifier", ko: "묶이지 않은 널리파이어" },
    AttackScratch { en: "Played in scratch pools in memory, each starting empty with two funded wallets, mallory and victim. Your ledger and wallets are not touched.", ko: "메모리 안의 임시 풀에서 합니다. 풀마다 비어 있는 상태에서 돈이 든 지갑 둘, mallory와 victim으로 시작합니다. 여러분의 원장과 지갑은 건드리지 않습니다." },
    IntroDoubleSpend { en: "mallory spends a note, then tries to spend it again with a fresh, valid proof.", ko: "mallory가 노트 하나를 쓴 뒤, 새로 만든 유효한 증명으로 같은 노트를 다시 쓰려 합니다." },
    IntroSteal { en: "mallory tries to spend victim's note without victim's spending key.", ko: "mallory가 victim의 지출 키 없이 victim의 노트를 쓰려 합니다." },
    IntroCounterfeit { en: "mallory tries to create value with a negative output: first against the honest circuit, then against a circuit without range checks. That broken circuit is a simple flaw of the same kind as BCTV14's CVE-2019-7167 (/forge bctv14), not the same bug.", ko: "mallory가 음수 출력으로 금액을 만들어 내려 합니다. 먼저 정직한 회로에, 그다음 범위 확인을 뺀 회로에 대해 해 봅니다. 그 고장 난 회로는 BCTV14의 CVE-2019-7167(/forge bctv14)과 같은 종류의 단순한 결함이지, 같은 버그는 아닙니다." },
    IntroUnboundNullifier { en: "mallory tries to spend one note twice under two nullifiers: first against the honest circuit, then against one that does not bind the nullifier to the note. That broken circuit is a simple flaw of the same kind as the Zcash Orchard circuit bug found on 2026-05-29, not the same bug.", ko: "mallory가 노트 하나를 서로 다른 널리파이어 둘로 두 번 쓰려 합니다. 먼저 정직한 회로에, 그다음 널리파이어를 노트에 묶지 않는 회로에 대해 해 봅니다. 그 고장 난 회로는 2026-05-29에 발견된 Zcash Orchard 회로 버그와 같은 종류의 단순한 결함이지, 같은 버그는 아닙니다." },
    StepAttackerShields { en: "mallory shields {amount}", ko: "mallory 가리기 · {amount}" },
    StepVictimShields { en: "victim shields {amount}", ko: "victim 가리기 · {amount}" },
    StepSpendNote { en: "mallory spends a note honestly", ko: "mallory가 노트 하나를 정직하게 씁니다" },
    StepRespend { en: "mallory spends the same note again with a fresh, valid proof", ko: "mallory가 새로 만든 유효한 증명으로 같은 노트를 다시 씁니다" },
    StepSteal { en: "mallory spends victim's note with mallory's own key", ko: "mallory가 자기 키로 victim의 노트를 씁니다" },
    StepNegative { en: "mallory spends a note into {first} and {second}", ko: "mallory가 노트 하나를 두 출력으로 나눠 씁니다: {first}, {second}" },
    StepUnshieldAll { en: "mallory takes {amount} out of the pool", ko: "mallory가 풀에서 꺼냅니다: {amount}" },
    StepFreshNullifier { en: "mallory spends the spent note again under a random nullifier", ko: "mallory가 이미 쓴 노트를 무작위 널리파이어로 다시 씁니다" },
    CircuitHonest { en: "honest circuit", ko: "정직한 회로" },
    CircuitNoRange { en: "circuit without range checks", ko: "범위 확인이 없는 회로" },
    CircuitUnbound { en: "circuit without the nullifier binding", ko: "널리파이어 묶기가 없는 회로" },
    StepRecorded { en: "recorded", ko: "기록됨" },
    StepRefused { en: "refused: {reasons}", ko: "거절됨: {reasons}" },
    StepVerifier { en: "verifier: {verdict}", ko: "검증자: {verdict}" },
    WordAccepted { en: "accepted", ko: "받아들임" },
    WordRejected { en: "rejected", ko: "거절" },
    WordUnreadable { en: "unreadable", ko: "읽을 수 없음" },
    StepBroken { en: "assertions the proved values break: {labels}", ko: "증명된 값이 깨는 단언: {labels}" },
    StepAfter { en: "value in the pool {pool} · mallory's shielded balance {attacker} · nullifiers {nullifiers}", ko: "풀 안의 금액 {pool} · mallory의 가린 잔액 {attacker} · 널리파이어 {nullifiers}" },
    AttackHeld { en: "The ledger running the honest circuit refused every forgery.", ko: "정직한 회로를 쓰는 원장이 모든 위조를 거절했습니다." },
    AttackBroken { en: "The ledger running the honest circuit accepted a forgery.", ko: "정직한 회로를 쓰는 원장이 위조를 받아들였습니다." },
    ReasonProof { en: "the proof does not verify", ko: "증명이 검증되지 않음" },
    ReasonRoot { en: "the anchor is not a root the ledger has had", ko: "앵커가 원장에 있었던 루트가 아님" },
    ReasonNullifier { en: "the nullifier was already published", ko: "널리파이어가 이미 공개됨" },
    ReasonFunds { en: "the transparent account cannot pay", ko: "투명 계정이 낼 수 없음" },
    ReasonTurnstile { en: "the value in the pool would go below zero, {before} → {after}", ko: "풀 안의 금액이 0 아래로 내려감, {before} → {after}" },
    ReasonTree { en: "the tree is full", ko: "트리가 가득 참" },
}
