//! Words for the Toy Shielded Pool: actions, receipts, the ledger, wallets and attacks.

zk_i18n::messages! {
    Subject { en: "the Toy Shielded Pool" },
    Disclaimer { en: "Toy Shielded Pool: an unofficial toy after Zcash's Sapling and Orchard designs, not affiliated with Zcash. No network, no real value." },
    HelpTitle { en: "Toy Shielded Pool" },
    HelpUse { en: "prove with Groth16, as Sapling does, or Halo 2, as Orchard does" },
    HelpWalletNew { en: "create a wallet: a spending key and its address" },
    HelpWallet { en: "what only this wallet's owner sees" },
    HelpWallets { en: "every wallet with its balances" },
    HelpFaucet { en: "give a wallet transparent coins, in the open" },
    HelpShield { en: "move transparent coins into a shielded note" },
    HelpSend { en: "pay from one wallet's note to another wallet" },
    HelpUnshield { en: "take coins out of a note, back into the open" },
    HelpLedger { en: "what the world sees" },
    HelpAttack { en: "try to break the pool, in scratch pools" },
    HelpReset { en: "delete this system's ledger and wallets" },
    NoDataDir { en: "There is no directory to keep the pool in. Set HOME or pass --data-dir." },
    ConfirmReset { en: "This deletes the {system} pool's ledger and every wallet in it. Type /pool reset --yes, or run nmtzk pool reset --yes, to go ahead." },
    ResetPrompt { en: "Delete the {system} pool's ledger and every wallet in it? Type yes to go ahead:" },
    ResetKept { en: "Nothing was deleted." },
    ResetDone { en: "The {system} pool is empty again." },
    Chosen { en: "The pool now proves with {system}. Each proof system keeps its own ledger and wallets." },
    ChosenDir { en: "Kept in {dir}" },
    Stopped { en: "Stopped before the ledger decided. Nothing was recorded." },
    ErrInvalidName { en: "'{name}' cannot be a wallet name. Use 1 to 32 of a–z, 0–9, - and _." },
    ErrWalletExists { en: "A wallet named {name} already exists." },
    ErrUnknownWallet { en: "No wallet is named {name}. /pool wallets lists them." },
    ErrZeroAmount { en: "The amount must be at least 1." },
    ErrNotEnoughTransparent { en: "{name} has {balance} transparent coins and cannot shield {amount}." },
    ErrNoNoteLargeEnough { en: "{name} has no single note of at least {amount}. The largest holds {largest}, and a spend uses one note." },
    ErrStorage { en: "The pool's files could not be read or written: {why}" },
    ErrCorrupt { en: "The pool's files do not describe a valid pool: {why}" },
    ErrMismatch { en: "This ledger belongs to {found}, not to {expected}." },
    ErrCircuit { en: "The spend circuit failed: {why}" },
    ErrRandomness { en: "The operating system gave no randomness: {why}" },
    ErrSystem { en: "The proof system failed: {why}" },
    ProvingShield { en: "{name} shields {amount} with {system}" },
    ProvingSend { en: "{from} sends {amount} to {to} with {system}" },
    ProvingUnshield { en: "{name} unshields {amount} with {system}" },
    ProvingAttack { en: "Attack: {attack}, with {system}" },
    WorkingProve { en: "Proving with {system}; the first proof also builds its keys" },
    ReceiptNewWallet { en: "{name} has a new wallet" },
    ReceiptFaucet { en: "The faucet gave {name} {amount} transparent coins · transaction {index}" },
    ReceiptShield { en: "{name} shielded {amount} · transaction {index}" },
    ReceiptSend { en: "{from} sent {amount} to {to} · transaction {index}" },
    ReceiptUnshield { en: "{name} unshielded {amount} · transaction {index}" },
    ReceiptRefused { en: "The ledger refused this transaction. Nothing was recorded." },
    WorldHeading { en: "What the world sees" },
    WorldNothing { en: "nothing: a new key never reaches the ledger" },
    OwnerHeading { en: "What only the wallets see" },
    OwnerNothing { en: "nothing: a faucet happens in the open" },
    FieldKind { en: "kind" },
    FieldTransparent { en: "transparent" },
    FieldAnchor { en: "anchor" },
    FieldNullifier { en: "nullifier" },
    FieldCommitments { en: "new note commitments" },
    FieldValue { en: "public value" },
    FieldProof { en: "proof" },
    FieldTiming { en: "time" },
    FieldPositions { en: "tree positions" },
    FieldAddress { en: "address" },
    FieldKey { en: "spending key" },
    FieldInput { en: "spent note" },
    FieldOutput { en: "note {number}" },
    KindFaucet { en: "faucet" },
    KindShield { en: "shield" },
    KindShieldedTransfer { en: "shielded transfer" },
    KindUnshield { en: "unshield" },
    TransparentCredit { en: "{account} receives {amount}" },
    TransparentDebit { en: "{account} pays {amount}" },
    ValueInOut { en: "{in} in, {out} out" },
    Timing { en: "proved in {prove}, verified in {verify}" },
    KeyKept { en: "stays in {name}'s wallet file" },
    InputDummy { en: "a zero-value note under a throwaway key: a shield spends no note" },
    InputNote { en: "{owner}'s note of {value} at position {position}" },
    InputNoteOtherKey { en: "{owner}'s note of {value} at position {position}, spent with {holder}'s key" },
    OutputTo { en: "{value} to {recipient}" },
    OutputNobody { en: "{value} to an address nobody holds" },
    OutputPosition { en: "position {position}" },
    DeliveryHanded { en: "handed to the wallet file on this machine" },
    DeliveryDiscarded { en: "kept by nobody" },
    VerifierAccepted { en: "{system}'s verifier accepts the proof." },
    VerifierRejected { en: "{system}'s verifier rejects the proof." },
    VerifierMalformed { en: "{system}'s verifier could not read the proof: {why}" },
    RulesHeading { en: "Rules the ledger applied" },
    RuleProof { en: "the proof verifies" },
    RuleRoot { en: "the anchor is a root the ledger has had" },
    RuleNullifier { en: "the nullifier was not published before" },
    RuleFunds { en: "the transparent account can pay what goes in" },
    RuleTurnstile { en: "the value in the pool stays at zero or above: {before} → {after}" },
    RuleTree { en: "the tree has room for two more notes" },
    KeysBuilt { en: "{system} keys were built first, in {time}." },
    LedgerTitle { en: "The ledger · {system} · what the world sees" },
    LedgerCircuit { en: "circuit" },
    LedgerPoolValue { en: "value in the pool" },
    LedgerTree { en: "notes in the tree" },
    LedgerTreeValue { en: "{used} of {capacity}" },
    LedgerRoot { en: "root" },
    LedgerNullifiers { en: "nullifiers published" },
    LedgerTransparent { en: "transparent balances" },
    LedgerNone { en: "none" },
    LedgerEmpty { en: "No transactions yet." },
    ColIndex { en: "#" },
    ColKind { en: "Kind" },
    ColTransparent { en: "Transparent" },
    ColNullifier { en: "Nullifier" },
    ColNotes { en: "New notes" },
    ColProof { en: "Proof" },
    WalletTitle { en: "Wallet {name} · {system} · what only {name} sees" },
    WalletShielded { en: "shielded balance" },
    WalletTransparent { en: "transparent balance" },
    WalletTransparentPublic { en: "public: the ledger shows it" },
    WalletNoNotes { en: "No notes yet." },
    ColNote { en: "Note" },
    ColValue { en: "Value" },
    ColPosition { en: "Position" },
    ColReceived { en: "From tx" },
    ColState { en: "State" },
    ColCommitment { en: "Commitment" },
    StateSpent { en: "spent" },
    StateUnspent { en: "unspent" },
    WalletsTitle { en: "Wallets · {system}" },
    WalletsEmpty { en: "No wallets yet. /pool wallet new <name> creates one." },
    ColName { en: "Name" },
    ColShielded { en: "Shielded" },
    ColNoteCount { en: "Notes" },
    AttackTitle { en: "Attack: {attack} · {system}" },
    AttackDoubleSpend { en: "double spend" },
    AttackSteal { en: "steal" },
    AttackCounterfeit { en: "counterfeit" },
    AttackUnboundNullifier { en: "unbound nullifier" },
    AttackScratch { en: "Played in scratch pools in memory, each starting empty with two funded wallets, mallory and victim. Your ledger and wallets are not touched." },
    IntroDoubleSpend { en: "mallory spends a note, then tries to spend it again with a fresh, valid proof." },
    IntroSteal { en: "mallory tries to spend victim's note without victim's spending key." },
    IntroCounterfeit { en: "mallory tries to create value with a negative output: first against the honest circuit, then against a circuit without range checks. That broken circuit is a simple flaw of the same kind as BCTV14's CVE-2019-7167 (/forge bctv14), not the same bug." },
    IntroUnboundNullifier { en: "mallory tries to spend one note twice under two nullifiers: first against the honest circuit, then against one that does not bind the nullifier to the note. That broken circuit is a simple flaw of the same kind as the Zcash Orchard circuit bug found on 2026-05-29, not the same bug." },
    StepAttackerShields { en: "mallory shields {amount}" },
    StepVictimShields { en: "victim shields {amount}" },
    StepSpendNote { en: "mallory spends a note honestly" },
    StepRespend { en: "mallory spends the same note again with a fresh, valid proof" },
    StepSteal { en: "mallory spends victim's note with mallory's own key" },
    StepNegative { en: "mallory spends a note into {first} and {second}" },
    StepUnshieldAll { en: "mallory takes {amount} out of the pool" },
    StepFreshNullifier { en: "mallory spends the spent note again under a random nullifier" },
    CircuitHonest { en: "honest circuit" },
    CircuitNoRange { en: "circuit without range checks" },
    CircuitUnbound { en: "circuit without the nullifier binding" },
    StepRecorded { en: "recorded" },
    StepRefused { en: "refused: {reasons}" },
    StepVerifier { en: "verifier: {verdict}" },
    WordAccepted { en: "accepted" },
    WordRejected { en: "rejected" },
    WordUnreadable { en: "unreadable" },
    StepBroken { en: "assertions the proved values break: {labels}" },
    StepAfter { en: "value in the pool {pool} · mallory's shielded balance {attacker} · nullifiers {nullifiers}" },
    AttackHeld { en: "The ledger running the honest circuit refused every forgery." },
    AttackBroken { en: "The ledger running the honest circuit accepted a forgery." },
    ReasonProof { en: "the proof does not verify" },
    ReasonRoot { en: "the anchor is not a root the ledger has had" },
    ReasonNullifier { en: "the nullifier was already published" },
    ReasonFunds { en: "the transparent account cannot pay" },
    ReasonTurnstile { en: "the value in the pool would go below zero, {before} → {after}" },
    ReasonTree { en: "the tree is full" },
}
