//! Words for a run: what it is doing, what it found, and how every system compares.

zk_i18n::messages! {
    Running { en: "Running {system} on {example}", ko: "실행 중 · {system} · {example}" },
    StageStarting { en: "Starting {system}", ko: "시작 · {system}" },
    StageSetup { en: "Setting up {system}", ko: "설정 중 · {system}" },
    StageProve { en: "Proving with {system}", ko: "증명 중 · {system}" },
    StageVerify { en: "Verifying with {system}", ko: "검증 중 · {system}" },
    StageFlip { en: "Attacking {system}: flipping a proof byte", ko: "공격 중 · {system} · 증명 바이트 뒤집기" },
    StageBump { en: "Attacking {system}: changing a public input", ko: "공격 중 · {system} · 공개 입력 바꾸기" },
    StageDishonest { en: "Attacking {system}: proving a false claim", ko: "공격 중 · {system} · 거짓 주장 증명" },
    StageRound { en: "Round {round} of {of} with {system}", ko: "라운드 {round} / {of} · {system}" },
    AfterSetup { en: "setup", ko: "설정" },
    AfterProve { en: "proving", ko: "증명" },
    AfterVerify { en: "verification", ko: "검증" },
    AfterFlip { en: "the flipped-byte attack", ko: "바이트 뒤집기 공격" },
    AfterBump { en: "the public-input attack", ko: "공개 입력 공격" },
    AfterDishonest { en: "the false-claim attack", ko: "거짓 주장 공격" },
    AfterRound { en: "round {round} of {of}", ko: "라운드 {round} / {of}" },
    Accepted { en: "{system} accepted the honest proof of {example}", ko: "정직한 증명을 받아들였습니다 · {system} · {example}" },
    Rejected { en: "{system} rejected the honest proof of {example}", ko: "정직한 증명을 거절했습니다 · {system} · {example}" },
    Malformed { en: "{system} could not read its own proof of {example}: {why}", ko: "자기 증명을 읽지 못했습니다 · {system} · {example}: {why}" },
    Circuit { en: "Circuit", ko: "회로" },
    CircuitForm { en: "{form} over {field}", ko: "{form} · 필드 {field}" },
    FormR1cs { en: "R1CS", ko: "R1CS" },
    FormPlonkish { en: "PLONKish rows", ko: "PLONK식 행" },
    FormWideAir { en: "wide AIR", ko: "넓은 AIR" },
    FormAcir { en: "ACIR", ko: "ACIR" },
    FormProgram { en: "VM program", ko: "VM 프로그램" },
    FormNative { en: "the system's own form", ko: "시스템 고유의 형태" },
    CountConstraints { en: "constraints", ko: "제약" },
    CountVariables { en: "variables", ko: "변수" },
    CountPublicInputs { en: "public inputs", ko: "공개 입력" },
    CountPrivateInputs { en: "private inputs", ko: "비공개 입력" },
    CountRows { en: "rows", ko: "행" },
    CountColumns { en: "columns", ko: "열" },
    CountGates { en: "gates", ko: "게이트" },
    CountMultiplications { en: "multiplications", ko: "곱셈" },
    CountPaddedConstraints { en: "padded constraints", ko: "채운 뒤 제약" },
    CountPaddedVariables { en: "padded variables", ko: "채운 뒤 변수" },
    CountPaddedWitnessVariables { en: "padded witness variables", ko: "채운 뒤 증인 변수" },
    CountDomainSize { en: "domain size", ko: "영역 크기" },
    CountCopyConstraints { en: "copy constraints", ko: "복사 제약" },
    CountAssertions { en: "assertions", ko: "단언" },
    CountWitnessValues { en: "witness values", ko: "증인 값" },
    CountWrapperConstraints { en: "wrapper constraints", ko: "감싸기 제약" },
    CountWitnessWords { en: "witness words", ko: "증인 워드" },
    CountPublicWords { en: "public words", ko: "공개 워드" },
    CountUniversalSrsBytes { en: "universal SRS bytes", ko: "범용 SRS 바이트" },
    CountTraceRows { en: "trace rows", ko: "트레이스 행" },
    CountSteps { en: "steps", ko: "단계" },
    CountAugmentedConstraints { en: "augmented-circuit constraints", ko: "증강 회로 제약" },
    CountSecondaryConstraints { en: "secondary-circuit constraints", ko: "보조 회로 제약" },
    CountRangeLookups { en: "range lookups", ko: "범위 룩업" },
    CountRangeChecks { en: "range checks", ko: "범위 확인" },
    CountLinearConstraints { en: "linear constraints", ko: "일차 제약" },
    CountQuadraticConstraints { en: "quadratic constraints", ko: "이차 제약" },
    CountProgramOperations { en: "program operations", ko: "프로그램 연산" },
    CountOpenedColumns { en: "opened columns", ko: "여는 열" },
    CountMultipliers { en: "multipliers", ko: "곱셈기" },
    CountMessageLength { en: "message length", ko: "메시지 길이" },
    CountLayers { en: "layers", ko: "층" },
    CountK { en: "k, log₂ of the rows", ko: "k(행 수의 log₂)" },
    CountGenerators { en: "generators", ko: "생성원" },
    CountCommitments { en: "commitments", ko: "약속" },
    Timings { en: "Timings", ko: "시간" },
    Measured { en: "measured on this machine, now", ko: "지금 이 기계에서 잰 값" },
    TimeSetup { en: "setup", ko: "설정" },
    TimeProve { en: "prove", ko: "증명" },
    TimeVerify { en: "verify", ko: "검증" },
    VerifyInConversation { en: "part of the conversation", ko: "대화의 일부" },
    Rounds { en: "rounds played", ko: "진행한 라운드" },
    Sizes { en: "Sizes", ko: "크기" },
    SetupMaterial { en: "setup material", ko: "설정 자료" },
    NoSetupMaterial { en: "none counted", ko: "센 것 없음" },
    Proof { en: "proof", ko: "증명" },
    Transcript { en: "transcript", ko: "대화 기록" },
    ProofHead { en: "First bytes", ko: "앞부분 바이트" },
    ProofHeadCount { en: "{shown} of {total} bytes", ko: "{total}바이트 중 {shown}바이트" },
    Attacks { en: "Attacks", ko: "공격" },
    AttacksHeld { en: "{held} of {total} held", ko: "{total}개 중 {held}개 막음" },
    AttacksSkipped { en: "not run", ko: "실행 안 함" },
    AttackFlipAt { en: "flip proof byte {offset}", ko: "증명 바이트 {offset} 뒤집기" },
    AttackFlip { en: "flip a proof byte", ko: "증명 바이트 하나 뒤집기" },
    AttackBump { en: "add 1 to a public input", ko: "공개 입력에 1 더하기" },
    AttackDishonest { en: "prove a false claim", ko: "거짓 주장 증명" },
    OutcomeRejected { en: "rejected", ko: "거절됨" },
    OutcomeMalformed { en: "rejected, could not be decoded: {why}", ko: "거절됨, 해독할 수 없음: {why}" },
    OutcomeRefused { en: "the prover refused: {why}", ko: "증명자가 거부함: {why}" },
    OutcomeAccepted { en: "ACCEPTED: this system is broken", ko: "받아들여짐: 이 시스템은 고장났습니다" },
    OutcomeMalleable { en: "accepted: the proof is malleable at this byte, which is not by itself a break", ko: "받아들여짐: 이 바이트에서 증명이 가변적이며, 그것만으로 고장은 아닙니다" },
    OutcomeNotApplicable { en: "not applicable: {why}", ko: "해당 없음: {why}" },
    Scan { en: "Secret scan", ko: "비밀 흔적 검사" },
    ScanNotFound { en: "no secret appears byte for byte in the proof", ko: "증명 안에 비밀이 바이트 그대로 나타나지 않습니다" },
    ScanFound { en: "found byte for byte in the proof: {names}", ko: "증명 안에서 바이트 그대로 찾음: {names}" },
    ScanFoundExpected { en: "expected: this system is not zero-knowledge as run here", ko: "예상한 결과: 이 시스템은 여기서 돌리는 설정으로는 영지식이 아닙니다" },
    ScanInconclusive { en: "every secret here is below 65,536, small enough to turn up in any proof by chance, so the scan cannot tell", ko: "여기 비밀은 모두 65,536보다 작아서 어떤 증명에든 우연히 나타날 수 있으므로, 검사로는 판단할 수 없습니다" },
    ScanSmoke { en: "A smoke detector, not a proof of zero knowledge.", ko: "연기 감지기일 뿐, 영지식의 증명이 아닙니다." },
    Adapted { en: "Adapted statement: {note}", ko: "고친 문장: {note}" },
    Unsupported { en: "{system} does not prove {example}: {reason}", ko: "증명하지 않는 문장 · {system} · {example}: {reason}" },
    StoppedAfter { en: "Stopped {system} after {stage}.", ko: "멈춤 · {system} · {stage} 뒤" },
    StoppedBefore { en: "Stopped {system} before setup finished.", ko: "멈춤 · {system} · 설정이 끝나기 전" },
    Failed { en: "{system} failed during {stage}: {error}", ko: "실패 · {system} · {stage} 중: {error}" },
    NoRandomness { en: "The operating system gave no randomness: {why}", ko: "운영체제가 난수를 주지 않았습니다: {why}" },
    ErrCancelled { en: "stopped on request", ko: "요청에 따라 멈춤" },
    ErrUnsatisfied { en: "the prover refused a false claim: {why}", ko: "증명자가 거짓 주장을 거부함: {why}" },
    ErrNotApplicable { en: "not applicable: {why}", ko: "해당 없음: {why}" },
    ErrCompanionMissing { en: "{executable} is not installed", ko: "설치돼 있지 않음: {executable}" },
    CompareTitle { en: "Every system on {example}", ko: "모든 시스템 · {example}" },
    ColSystem { en: "System", ko: "시스템" },
    ColShelf { en: "Shelf", ko: "선반" },
    ColSetup { en: "Setup", ko: "설정" },
    ColProve { en: "Prove", ko: "증명" },
    ColVerify { en: "Verify", ko: "검증" },
    ColProof { en: "Proof", ko: "증명 크기" },
    ColVerdict { en: "Verdict", ko: "판정" },
    ColAttacks { en: "Attacks", ko: "공격" },
    ColSecrets { en: "Secrets", ko: "비밀" },
    RowWaiting { en: "waiting", ko: "대기" },
    RowRunning { en: "running", ko: "실행 중" },
    RowSkipped { en: "skipped", ko: "건너뜀" },
    RowAccepted { en: "accepted", ko: "받아들임" },
    RowRejected { en: "rejected", ko: "거절" },
    RowFailed { en: "failed", ko: "실패" },
    RowUnsupported { en: "unsupported", ko: "지원 안 함" },
    RowStopped { en: "stopped", ko: "멈춤" },
    SecretsNone { en: "none", ko: "없음" },
    SecretsFound { en: "found", ko: "찾음" },
    SecretsUnknown { en: "n/a", ko: "해당 없음" },
    CompareSummary { en: "{sound} of {total} accepted the honest proof and held every attack.", ko: "{total}개 중 {sound}개가 정직한 증명을 받아들이고 모든 공격을 막았습니다." },
    CompareTimes { en: "Times measured on this machine, now.", ko: "시간은 지금 이 기계에서 잰 값입니다." },
    CompareSecrets { en: "Secrets is a smoke detector, not a proof of zero knowledge.", ko: "비밀 열은 연기 감지기일 뿐, 영지식의 증명이 아닙니다." },
    CompareDetails { en: "/run <system> {example} shows one system in full.", ko: "/run <시스템> {example} — 시스템 하나를 자세히 봅니다." },
}
