//! Words for a run: what it is doing, what it found, and how every system compares.

zk_i18n::messages! {
    Running { en: "Running {system} on {example}" },
    StageStarting { en: "Starting {system}" },
    StageSetup { en: "Setting up {system}" },
    StageProve { en: "Proving with {system}" },
    StageVerify { en: "Verifying with {system}" },
    StageFlip { en: "Attacking {system}: flipping a proof byte" },
    StageBump { en: "Attacking {system}: changing a public input" },
    StageDishonest { en: "Attacking {system}: proving a false claim" },
    StageRound { en: "Round {round} of {of} with {system}" },
    AfterSetup { en: "setup" },
    AfterProve { en: "proving" },
    AfterVerify { en: "verification" },
    AfterFlip { en: "the flipped-byte attack" },
    AfterBump { en: "the public-input attack" },
    AfterDishonest { en: "the false-claim attack" },
    AfterRound { en: "round {round} of {of}" },
    Accepted { en: "{system} accepted the honest proof of {example}" },
    Rejected { en: "{system} rejected the honest proof of {example}" },
    Malformed { en: "{system} could not read its own proof of {example}: {why}" },
    Circuit { en: "Circuit" },
    CircuitForm { en: "{form} over {field}" },
    FormR1cs { en: "R1CS" },
    FormPlonkish { en: "PLONKish rows" },
    FormWideAir { en: "wide AIR" },
    FormAcir { en: "ACIR" },
    FormProgram { en: "VM program" },
    FormNative { en: "the system's own form" },
    CountConstraints { en: "constraints" },
    CountVariables { en: "variables" },
    CountPublicInputs { en: "public inputs" },
    CountPrivateInputs { en: "private inputs" },
    CountRows { en: "rows" },
    CountColumns { en: "columns" },
    CountGates { en: "gates" },
    CountMultiplications { en: "multiplications" },
    Timings { en: "Timings" },
    Measured { en: "measured on this machine, now" },
    TimeSetup { en: "setup" },
    TimeProve { en: "prove" },
    TimeVerify { en: "verify" },
    VerifyInConversation { en: "part of the conversation" },
    Rounds { en: "rounds played" },
    Sizes { en: "Sizes" },
    SetupMaterial { en: "setup material" },
    NoSetupMaterial { en: "none counted" },
    Proof { en: "proof" },
    Transcript { en: "transcript" },
    ProofHead { en: "First bytes" },
    ProofHeadCount { en: "{shown} of {total} bytes" },
    Attacks { en: "Attacks" },
    AttacksHeld { en: "{held} of {total} held" },
    AttacksSkipped { en: "not run" },
    AttackFlipAt { en: "flip proof byte {offset}" },
    AttackFlip { en: "flip a proof byte" },
    AttackBump { en: "add 1 to a public input" },
    AttackDishonest { en: "prove a false claim" },
    OutcomeRejected { en: "rejected" },
    OutcomeMalformed { en: "rejected, could not be decoded: {why}" },
    OutcomeRefused { en: "the prover refused: {why}" },
    OutcomeAccepted { en: "ACCEPTED: this system is broken" },
    OutcomeMalleable { en: "accepted: the proof is malleable at this byte, which is not by itself a break" },
    OutcomeNotApplicable { en: "not applicable: {why}" },
    Scan { en: "Secret scan" },
    ScanNotFound { en: "no secret appears byte for byte in the proof" },
    ScanFound { en: "found byte for byte in the proof: {names}" },
    ScanFoundExpected { en: "expected: this system is not zero-knowledge as run here" },
    ScanInconclusive { en: "every secret here is below 65,536, small enough to turn up in any proof by chance, so the scan cannot tell" },
    ScanSmoke { en: "A smoke detector, not a proof of zero knowledge." },
    Adapted { en: "Adapted statement: {note}" },
    Unsupported { en: "{system} does not prove {example}: {reason}" },
    StoppedAfter { en: "Stopped {system} after {stage}." },
    StoppedBefore { en: "Stopped {system} before setup finished." },
    Failed { en: "{system} failed during {stage}: {error}" },
    NoRandomness { en: "The operating system gave no randomness: {why}" },
    ErrCancelled { en: "stopped on request" },
    ErrUnsatisfied { en: "the prover refused a false claim: {why}" },
    ErrNotApplicable { en: "not applicable: {why}" },
    ErrCompanionMissing { en: "{executable} is not installed" },
    CompareTitle { en: "Every system on {example}" },
    ColSystem { en: "System" },
    ColShelf { en: "Shelf" },
    ColSetup { en: "Setup" },
    ColProve { en: "Prove" },
    ColVerify { en: "Verify" },
    ColProof { en: "Proof" },
    ColVerdict { en: "Verdict" },
    ColAttacks { en: "Attacks" },
    ColSecrets { en: "Secrets" },
    RowWaiting { en: "waiting" },
    RowRunning { en: "running" },
    RowSkipped { en: "skipped" },
    RowAccepted { en: "accepted" },
    RowRejected { en: "rejected" },
    RowFailed { en: "failed" },
    RowUnsupported { en: "unsupported" },
    RowStopped { en: "stopped" },
    SecretsNone { en: "none" },
    SecretsFound { en: "found" },
    SecretsUnknown { en: "n/a" },
    CompareSummary { en: "{sound} of {total} accepted the honest proof and held every attack." },
    CompareTimes { en: "Times measured on this machine, now." },
    CompareSecrets { en: "Secrets is a smoke detector, not a proof of zero knowledge." },
    CompareDetails { en: "/run <system> {example} shows one system in full." },
}
