//! Words for Trio's rounds: the cards, what a round opens, every check and the odds.

zk_i18n::messages! {
    Title { en: "Trio: {mode} · {example} · {rounds} rounds" },
    ModePlay { en: "an honest prover" },
    ModeCheat { en: "a cheat, {cheat}" },
    ModeSimulate { en: "the simulator" },
    CheatBadCard { en: "a bad card" },
    CheatBadComputation { en: "a bad computation" },
    CheatRewriteHidden { en: "rewritten hidden shares" },
    IntroPlay { en: "The prover splits the secret among three imagined friends, who compute the circuit on their shares. Each round the prover commits first. Then the verifier draws one of five cards and checks what that card opens." },
    IntroCheat { en: "This prover has no true claim and tries to pass anyway. Each round it commits first, then the verifier draws one of five cards." },
    IntroSimulate { en: "The simulator has no secret. It is told every card in advance and prepares each round for its card." },
    LieBadCard { en: "The dealer rigs multiplication card {index} so the false claim's arithmetic adds up." },
    LieBadComputation { en: "Friend 2 sends messages that make every check sum to zero. They are not what friend 2 computed." },
    LieRewriteHidden { en: "After seeing a peek card, the prover rewrites the hidden friend's messages so every sum comes out zero. Trio's first draft could not catch this." },
    SourceExample { en: "The false claim is the example's own false statement." },
    SourceBumped { en: "The false claim is the true witness offered for public input {index} plus one." },
    PlannedCards { en: "Cards known in advance: {cards}" },
    CardShortDealerA { en: "A" },
    CardShortDealerB { en: "B" },
    CardShortPeek { en: "H{friend}" },
    RoundLabel { en: "Round {round}" },
    CardDealerA { en: "dealer card A" },
    CardDealerB { en: "dealer card B" },
    CardPeek { en: "peek card, friend {friend} hidden" },
    OpenedLabel { en: "opened" },
    OpenedCardSeed { en: "card seed {friend}" },
    OpenedInputSeed { en: "input seed {friend}" },
    OpenedCardCorrection { en: "card correction" },
    OpenedInputCorrection { en: "input correction" },
    OpenedViewKey { en: "view key {friend}" },
    OpenedBroadcasts { en: "messages of friend {friend}" },
    ChecksLabel { en: "checks" },
    CheckFits { en: "fits the card" },
    CheckMultiply { en: "c = a·b" },
    CheckCardCommitment { en: "K{friend}" },
    CheckViewCommitment { en: "V{friend}" },
    CheckSums { en: "sums are zero" },
    CaughtFits { en: "the opening did not fit the card" },
    CaughtMultiply { en: "multiplication card {index} does not satisfy c = a·b" },
    CaughtCardCommitment { en: "friend {friend}'s card seed does not match its commitment K{friend}" },
    CaughtViewCommitment { en: "friend {friend}'s messages do not match its commitment V{friend}" },
    CaughtSums { en: "check {index} does not sum to zero" },
    VerdictAccepted { en: "The verifier accepts after {rounds} rounds." },
    VerdictCaught { en: "Caught in round {round}: {why}." },
    VerdictEscaped { en: "The cheat was not caught in {rounds} rounds." },
    VerdictSimulated { en: "All {rounds} simulated rounds passed the same checks, and no secret was used." },
    SimulatedNote { en: "This worked only because the cards were known before each commitment. A live verifier draws each card after the commitment." },
    Odds { en: "A cheat gets through {rounds} rounds by luck with a chance of (3/5)^{rounds}, about 1 in {odds}." },
    Stopped { en: "Stopped after {done} of {total} rounds." },
    WorkingRound { en: "Round {round} of {total}" },
    Failed { en: "Trio could not run: {why}" },
}
