//! Words for Trio's rounds: the cards, what a round opens, every check and the odds.

zk_i18n::messages! {
    Title { en: "Trio: {mode} · {example} · {rounds} rounds", ko: "Trio: {mode} · {example} · 라운드 {rounds}" },
    ModePlay { en: "an honest prover", ko: "정직한 증명자" },
    ModeCheat { en: "a cheat, {cheat}", ko: "속이는 증명자 · {cheat}" },
    ModeSimulate { en: "the simulator", ko: "시뮬레이터" },
    CheatBadCard { en: "a bad card", ko: "나쁜 카드" },
    CheatBadComputation { en: "a bad computation", ko: "나쁜 계산" },
    CheatRewriteHidden { en: "rewritten hidden shares", ko: "숨긴 조각 고쳐 쓰기" },
    IntroPlay { en: "The prover splits the secret among three imagined friends, who compute the circuit on their shares. Each round the prover commits first. Then the verifier draws one of five cards and checks what that card opens.", ko: "증명자는 비밀을 상상 속 친구 셋에게 나눠 주고, 친구들은 자기 조각으로 회로를 계산합니다. 라운드마다 증명자가 먼저 약속합니다. 그다음 검증자가 카드 다섯 장 중 한 장을 뽑고, 그 카드가 여는 것을 확인합니다." },
    IntroCheat { en: "This prover has no true claim and tries to pass anyway. Each round it commits first, then the verifier draws one of five cards.", ko: "이 증명자에게는 참인 주장이 없는데도 통과하려 합니다. 라운드마다 먼저 약속하고, 그다음 검증자가 카드 다섯 장 중 한 장을 뽑습니다." },
    IntroSimulate { en: "The simulator has no secret. It is told every card in advance and prepares each round for its card.", ko: "시뮬레이터에게는 비밀이 없습니다. 모든 카드를 미리 듣고, 라운드마다 그 카드에 맞춰 준비합니다." },
    LieBadCard { en: "The dealer rigs multiplication card {index} so the false claim's arithmetic adds up.", ko: "딜러가 곱셈 카드 하나(번호 {index})를 조작해 거짓 주장의 계산이 맞아떨어지게 합니다." },
    LieBadComputation { en: "Friend 2 sends messages that make every check sum to zero. They are not what friend 2 computed.", ko: "친구 2가 모든 확인의 합을 0으로 만드는 메시지를 보냅니다. 친구 2가 실제로 계산한 값이 아닙니다." },
    LieRewriteHidden { en: "After seeing a peek card, the prover rewrites the hidden friend's messages so every sum comes out zero. Trio's first draft could not catch this.", ko: "엿보기 카드를 본 뒤 증명자가 숨긴 친구의 메시지를 고쳐 써서 모든 합이 0이 되게 합니다. Trio의 처음 설계는 이것을 잡지 못했습니다." },
    SourceExample { en: "The false claim is the example's own false statement.", ko: "거짓 주장은 예제에 들어 있는 거짓 문장입니다." },
    SourceBumped { en: "The false claim is the true witness offered for public input {index} plus one.", ko: "거짓 주장은 공개 입력 {index}에 1을 더한 문장에 참인 증인을 내미는 것입니다." },
    PlannedCards { en: "Cards known in advance: {cards}", ko: "미리 알고 있는 카드: {cards}" },
    CardShortDealerA { en: "A", ko: "A" },
    CardShortDealerB { en: "B", ko: "B" },
    CardShortPeek { en: "H{friend}", ko: "H{friend}" },
    RoundLabel { en: "Round {round}", ko: "라운드 {round}" },
    CardDealerA { en: "dealer card A", ko: "딜러 카드 A" },
    CardDealerB { en: "dealer card B", ko: "딜러 카드 B" },
    CardPeek { en: "peek card, friend {friend} hidden", ko: "엿보기 카드 · 친구 {friend} 숨김" },
    OpenedLabel { en: "opened", ko: "연 것" },
    OpenedCardSeed { en: "card seed {friend}", ko: "카드 씨앗 {friend}" },
    OpenedInputSeed { en: "input seed {friend}", ko: "입력 씨앗 {friend}" },
    OpenedCardCorrection { en: "card correction", ko: "카드 보정값" },
    OpenedInputCorrection { en: "input correction", ko: "입력 보정값" },
    OpenedViewKey { en: "view key {friend}", ko: "뷰 키 {friend}" },
    OpenedBroadcasts { en: "messages of friend {friend}", ko: "친구 {friend}의 메시지" },
    ChecksLabel { en: "checks", ko: "확인" },
    CheckFits { en: "fits the card", ko: "카드와 맞음" },
    CheckMultiply { en: "c = a·b", ko: "c = a·b" },
    CheckCardCommitment { en: "K{friend}", ko: "K{friend}" },
    CheckViewCommitment { en: "V{friend}", ko: "V{friend}" },
    CheckSums { en: "sums are zero", ko: "합이 0" },
    CaughtFits { en: "the opening did not fit the card", ko: "연 것이 카드와 맞지 않습니다" },
    CaughtMultiply { en: "multiplication card {index} does not satisfy c = a·b", ko: "곱셈 카드 {index}: c = a·b를 만족하지 않습니다" },
    CaughtCardCommitment { en: "friend {friend}'s card seed does not match its commitment K{friend}", ko: "친구 {friend}의 카드 씨앗이 약속과 맞지 않습니다 (K{friend})" },
    CaughtViewCommitment { en: "friend {friend}'s messages do not match its commitment V{friend}", ko: "친구 {friend}의 메시지가 약속과 맞지 않습니다 (V{friend})" },
    CaughtSums { en: "check {index} does not sum to zero", ko: "확인 {index}의 합이 0이 아닙니다" },
    VerdictAccepted { en: "The verifier accepts after {rounds} rounds.", ko: "라운드 {rounds}개 뒤 검증자가 받아들입니다." },
    VerdictCaught { en: "Caught in round {round}: {why}.", ko: "라운드 {round}에서 들켰습니다: {why}." },
    VerdictEscaped { en: "The cheat was not caught in {rounds} rounds.", ko: "라운드 {rounds}개 동안 속임수가 들키지 않았습니다." },
    VerdictSimulated { en: "All {rounds} simulated rounds passed the same checks, and no secret was used.", ko: "시뮬레이션한 라운드 {rounds}개가 모두 같은 확인을 통과했고, 비밀은 쓰이지 않았습니다." },
    SimulatedNote { en: "This worked only because the cards were known before each commitment. A live verifier draws each card after the commitment.", ko: "카드를 약속 전에 알았기 때문에만 된 일입니다. 실제 검증자는 약속 뒤에 카드를 뽑습니다." },
    Odds { en: "A cheat gets through {rounds} rounds by luck with a chance of (3/5)^{rounds}, about 1 in {odds}.", ko: "속임수가 운으로 라운드 {rounds}개를 통과할 확률: (3/5)^{rounds}, 약 {odds}분의 1." },
    Stopped { en: "Stopped after {done} of {total} rounds.", ko: "라운드 {total}개 중 {done}개 뒤에 멈췄습니다." },
    WorkingRound { en: "Round {round} of {total}", ko: "라운드 {round} / {total}" },
    Failed { en: "Trio could not run: {why}", ko: "Trio를 돌리지 못했습니다: {why}" },
}
