//! Words of the screen itself: the welcome box, the composer, the footer, keys and commands.

zk_i18n::messages! {
    WelcomeTagline { en: "A working museum of zero-knowledge proof systems." },
    WelcomeList { en: "every system, shelf by shelf" },
    WelcomeExamples { en: "the seven statements every system proves" },
    WelcomeRunAll { en: "prove that 1 + 1 = 2 with every system" },
    WelcomeLang { en: "read this program in Korean" },
    Placeholder { en: "Type / for commands, ? for shortcuts" },
    FooterHints { en: "/ commands · ? shortcuts · ctrl+c quit" },
    FooterQuitAgain { en: "press ctrl+c again to quit" },
    FooterNewOutput { en: "↓ new output" },
    FooterNothingToReopen { en: "nothing to reopen yet: /about opens a page" },
    WorkingStop { en: "esc to stop" },
    WorkingStopping { en: "stopping" },
    TooSmall { en: "Please enlarge the terminal to at least 60×16." },
    PagerClose { en: "q to close" },
    PagerKeys { en: "↑↓ j k scroll · PgUp PgDn page · g G top and bottom · q close" },
    ShortcutsTitle { en: "Keyboard shortcuts" },
    ShortcutsClose { en: "press any key to close" },
    KeyEnter { en: "run the command" },
    KeyNewline { en: "new line" },
    KeyTab { en: "complete from the list" },
    KeyUpDown { en: "move in the list, or recall earlier commands" },
    KeyEsc { en: "close the list, or stop a run" },
    KeyCtrlC { en: "clear the line; on an empty line, twice to quit" },
    KeyScroll { en: "scroll the transcript" },
    KeyCtrlO { en: "reopen the last page" },
    KeyCtrlL { en: "redraw the screen" },
    KeyShiftDrag { en: "select text (the mouse is captured for scrolling)" },
    KeyQuestion { en: "these shortcuts, on an empty line" },
    HelpCommands { en: "Commands" },
    HelpShortcutsHint { en: "Press ? on an empty line for keyboard shortcuts." },
    CmdHelp { en: "show the commands" },
    CmdList { en: "the systems on the shelves" },
    CmdAbout { en: "what a system is; opens its page" },
    CmdExamples { en: "the seven statements every system proves" },
    CmdRun { en: "prove, verify and attack an example" },
    CmdCave { en: "Ali Baba's cave, filmed scene by scene" },
    CmdTrio { en: "Trio's rounds: an honest prover, a cheat or the simulator" },
    CmdPool { en: "the Toy Shielded Pool; /pool alone lists what it does" },
    CmdCeremony { en: "a trusted-setup ceremony: toxic waste, Powers of Tau, collusion" },
    CmdForge { en: "replay a known forgery: CVE-2019-7167 in BCTV14" },
    CmdLang { en: "switch the language" },
    CmdClear { en: "clear the transcript" },
    CmdQuit { en: "leave nmtzk" },
    ArgAll { en: "every system, one after another" },
    ArgTrioCheat { en: "a prover who lies" },
    ArgToxic { en: "keys made from known toxic waste forge a proof" },
    ArgTau { en: "Powers of Tau, checked turn by turn, and two cheats caught" },
    ArgCollude { en: "every participant keeps the secret" },
    ArgBctv14 { en: "CVE-2019-7167: a BCTV14 proof rewritten for a false claim" },
    UnknownCommand { en: "Unknown command {command}. Type /help for the list." },
    NoSlash { en: "Commands start with /. Type /help for the list." },
    Usage { en: "Usage: {usage}" },
    UnknownShelf { en: "Unknown shelf '{shelf}'. Shelves: {shelves}." },
    UnknownExample { en: "Unknown example '{example}'. Type /examples for the list." },
    UnknownLanguage { en: "Unknown language '{language}'. Languages: {languages}." },
    UnknownChoice { en: "Unknown choice '{value}'. Choices: {choices}." },
    BadCount { en: "{flag} takes a whole number from 1 to {max}, not '{value}'." },
    BadAmount { en: "'{value}' is not an amount. Amounts are whole numbers from 0 to 65,535." },
    UnknownSystem { en: "Unknown system '{system}'. /list or nmtzk list shows the systems in this build." },
    Busy { en: "A run is still going. Press esc to stop it first." },
    LanguageSet { en: "Language: {language}" },
    Crashed { en: "The task stopped unexpectedly: {why}" },
}
