//! Words of the screen itself: the welcome box, the composer, the footer, keys and commands.

zk_i18n::messages! {
    WelcomeTagline { en: "A working museum of zero-knowledge proof systems.", ko: "영지식 증명 시스템의 움직이는 박물관입니다." },
    WelcomeList { en: "every system, shelf by shelf", ko: "선반마다 모든 시스템" },
    WelcomeExamples { en: "the seven statements every system proves", ko: "모든 시스템이 증명하는 일곱 문장" },
    WelcomeRunAll { en: "prove that 1 + 1 = 2 with every system", ko: "모든 시스템으로 1 + 1 = 2 증명하기" },
    WelcomeLang { en: "read this program in Korean", ko: "이 프로그램을 영어로 읽기" },
    Placeholder { en: "Type / for commands, ? for shortcuts", ko: "/를 치면 명령, ?를 치면 단축키" },
    FooterHints { en: "/ commands · ? shortcuts · ctrl+c quit", ko: "/ 명령 · ? 단축키 · ctrl+c 끝내기" },
    FooterQuitAgain { en: "press ctrl+c again to quit", ko: "끝내려면 ctrl+c를 한 번 더 누르세요" },
    FooterNewOutput { en: "↓ new output", ko: "↓ 새 출력" },
    FooterNothingToReopen { en: "nothing to reopen yet: /about opens a page", ko: "아직 다시 열 페이지가 없습니다: /about이 페이지를 엽니다" },
    WorkingStop { en: "esc to stop", ko: "esc로 멈추기" },
    WorkingStopping { en: "stopping", ko: "멈추는 중" },
    TooSmall { en: "Please enlarge the terminal to at least 60×16.", ko: "터미널을 60×16 이상으로 키워 주세요." },
    PagerClose { en: "q to close", ko: "q로 닫기" },
    PagerKeys { en: "↑↓ j k scroll · PgUp PgDn page · g G top and bottom · q close", ko: "↑↓ j k 스크롤 · PgUp PgDn 페이지 · g G 처음과 끝 · q 닫기" },
    ShortcutsTitle { en: "Keyboard shortcuts", ko: "키보드 단축키" },
    ShortcutsClose { en: "press any key to close", ko: "아무 키나 누르면 닫힙니다" },
    KeyEnter { en: "run the command", ko: "명령 실행" },
    KeyNewline { en: "new line", ko: "줄 바꿈" },
    KeyTab { en: "complete from the list", ko: "목록에서 완성" },
    KeyUpDown { en: "move in the list, or recall earlier commands", ko: "목록에서 이동, 또는 앞서 친 명령 불러오기" },
    KeyEsc { en: "close the list, or stop a run", ko: "목록 닫기, 또는 실행 멈추기" },
    KeyCtrlC { en: "clear the line; on an empty line, twice to quit", ko: "줄 지우기 · 빈 줄에서 두 번 누르면 끝내기" },
    KeyScroll { en: "scroll the transcript", ko: "기록 스크롤" },
    KeyCtrlO { en: "reopen the last page", ko: "마지막 페이지 다시 열기" },
    KeyCtrlL { en: "redraw the screen", ko: "화면 다시 그리기" },
    KeyShiftDrag { en: "select text (the mouse is captured for scrolling)", ko: "글자 선택(마우스는 스크롤에 쓰입니다)" },
    KeyQuestion { en: "these shortcuts, on an empty line", ko: "빈 줄에서 이 단축키 보기" },
    HelpCommands { en: "Commands", ko: "명령" },
    HelpShortcutsHint { en: "Press ? on an empty line for keyboard shortcuts.", ko: "빈 줄에서 ?를 누르면 키보드 단축키가 나옵니다." },
    CmdHelp { en: "show the commands", ko: "명령 보기" },
    CmdList { en: "the systems on the shelves", ko: "선반에 있는 시스템" },
    CmdAbout { en: "what a system is; opens its page", ko: "시스템 설명 · 페이지 열기" },
    CmdExamples { en: "the seven statements every system proves", ko: "모든 시스템이 증명하는 일곱 문장" },
    CmdRun { en: "prove, verify and attack an example", ko: "예제를 증명하고 검증하고 공격하기" },
    CmdCave { en: "Ali Baba's cave, filmed scene by scene", ko: "알리바바의 동굴, 장면마다 촬영" },
    CmdTrio { en: "Trio's rounds: an honest prover, a cheat or the simulator", ko: "Trio의 라운드: 정직한 증명자, 속이는 증명자, 시뮬레이터" },
    CmdPool { en: "the Toy Shielded Pool; /pool alone lists what it does", ko: "장난감 비공개 송금 · /pool만 치면 할 수 있는 일 목록" },
    CmdCeremony { en: "a trusted-setup ceremony: toxic waste, Powers of Tau, collusion", ko: "신뢰 설정 의식: 독성 폐기물, Powers of Tau, 담합" },
    CmdForge { en: "replay a known forgery: CVE-2019-7167 in BCTV14", ko: "알려진 위조 재현: BCTV14의 CVE-2019-7167" },
    CmdLang { en: "switch the language", ko: "언어 바꾸기" },
    CmdClear { en: "clear the transcript", ko: "기록 지우기" },
    CmdQuit { en: "leave nmtzk", ko: "nmtzk 끝내기" },
    ArgAll { en: "every system, one after another", ko: "모든 시스템을 차례로" },
    ArgTrioCheat { en: "a prover who lies", ko: "거짓말하는 증명자" },
    ArgToxic { en: "keys made from known toxic waste forge a proof", ko: "알려진 독성 폐기물로 만든 키가 증명을 위조합니다" },
    ArgTau { en: "Powers of Tau, checked turn by turn, and two cheats caught", ko: "차례마다 확인하는 Powers of Tau와, 잡히는 속임수 둘" },
    ArgCollude { en: "every participant keeps the secret", ko: "모든 참여자가 비밀을 간직합니다" },
    ArgBctv14 { en: "CVE-2019-7167: a BCTV14 proof rewritten for a false claim", ko: "CVE-2019-7167: 거짓 주장으로 고쳐 쓴 BCTV14 증명" },
    UnknownCommand { en: "Unknown command {command}. Type /help for the list.", ko: "모르는 명령: {command}. /help를 치면 목록이 나옵니다." },
    NoSlash { en: "Commands start with /. Type /help for the list.", ko: "명령은 /로 시작합니다. /help를 치면 목록이 나옵니다." },
    Usage { en: "Usage: {usage}", ko: "사용법: {usage}" },
    UnknownShelf { en: "Unknown shelf '{shelf}'. Shelves: {shelves}.", ko: "모르는 선반: '{shelf}'. 선반: {shelves}." },
    UnknownExample { en: "Unknown example '{example}'. Type /examples for the list.", ko: "모르는 예제: '{example}'. /examples를 치면 목록이 나옵니다." },
    UnknownLanguage { en: "Unknown language '{language}'. Languages: {languages}.", ko: "모르는 언어: '{language}'. 언어: {languages}." },
    UnknownChoice { en: "Unknown choice '{value}'. Choices: {choices}.", ko: "모르는 선택: '{value}'. 고를 수 있는 것: {choices}." },
    BadCount { en: "{flag} takes a whole number from 1 to {max}, not '{value}'.", ko: "{flag} 값은 1부터 {max}까지의 정수여야 합니다. 받은 값: '{value}'." },
    BadAmount { en: "'{value}' is not an amount. Amounts are whole numbers from 0 to 65,535.", ko: "금액이 아닙니다: '{value}'. 금액은 0부터 65,535까지의 정수입니다." },
    UnknownSystem { en: "Unknown system '{system}'. /list or nmtzk list shows the systems in this build.", ko: "모르는 시스템: '{system}'. /list나 nmtzk list가 이 빌드의 시스템을 보여 줍니다." },
    Busy { en: "A run is still going. Press esc to stop it first.", ko: "아직 실행 중입니다. 먼저 esc로 멈추세요." },
    LanguageSet { en: "Language: {language}", ko: "언어: {language}" },
    Crashed { en: "The task stopped unexpectedly: {why}", ko: "작업이 예상치 못하게 멈췄습니다: {why}" },
}
